### ISSUE TITLE
Add user to group during CreateUser operation

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-dotnet#131]
https://developer.okta.com/docs/api/resources/users.html#create-user-with-authentication-provider

**Comment by urielzen** [comment]
Is this still in the backburner?

**Comment by laura-rodriguez** [comment]
Closing since this was fixed already. See [`CreateUserRequest`](https://github.com/okta/okta-sdk-dotnet/blob/1849eb0d2b199d3e3fc2723bb4dc732c7b135352/src/Okta.Sdk/Generated/CreateUserRequest.Generated.cs).
