### ISSUE TITLE
Authentication in new sdk

### ISSUE THREAD

**Issue by RefractedPaladin** [okta/okta-sdk-dotnet#150]
Am I blind?  How do I Authenticate using the new SDK?  I could with the Legacy one...

**Comment by nbarbettini** [comment]
You're not blind. The new SDK doesn't include the [authn API](https://developer.okta.com/docs/api/resources/authn.html). It's focused on backend user management right now.

What's the use case you are trying to build out?

(Awesome avatar image, btw. 😄 )

**Comment by RefractedPaladin** [comment]
Thanks!
Use case is that I have to make a call, through our API, to Okta's API to Authn a User who passed a User/Pass to me.  I had used the SDK in the past so was hoping to just continue that but it sounds like I'll have to do my own thing.  RestSharp or something for the Authn Paths...

**Comment by nbarbettini** [comment]
We recommend OpenID Connect as a best practice for new applications, but I get that isn't always an option for brownfield work.

You should be able to call the Authentication API in the new SDK, even if it's not officially supported. The SDK exposes raw `Get`, `Post` etc methods that let you call any API you want. If for example you are calling [this API](https://developer.okta.com/docs/api/resources/authn.html#primary-authentication-with-trusted-application) to log in with username/password:

```csharp
try
{
    await client.PostAsync("/api/v1/authn", new
    {
        username = "test3@example.com",
        password = "Changeme123!!",
        options = new
        {
            multiOptionalFactorEnroll = false,
            warnBeforePasswordExpired = false,
        }
    });
}
catch (OktaApiException ex)
{
    // Login failed
    throw;
}

// Login succeeded
// Check response status property!
```

You can use `Post<TResponse>` to deserialize the response to a class you define (which must inherit from `Resource` - see examples such as [UserProfile](https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Generated/UserProfile.Generated.cs)).

Hopefully that's enough to get you started. Let me know if you have questions!

**Comment by RefractedPaladin** [comment]
Awesome info, thanks!
FWIW I had been planning to use OIDC, how would that be different than what you showed below? It still uses the authn endpoint, right?

Thanks
Patrick

**Comment by nbarbettini** [comment]
> FWIW I had been planning to use OIDC, how would that be different than what you showed below? It still uses the authn endpoint, right?

It doesn't use the Authn endpoint, it's a totally different type of interaction. Lee's [blog post](https://okta.github.io/blog/2017/06/29/oidc-user-auth-aspnet-core) is a good introduction. Tl;dr - use the OIDC middleware in your app pipeline.

I'll close this issue for now, but don't hesitate to hit us up at developers@okta.com if you have questions.
