### ISSUE TITLE
Second-level properties aren't serialized

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-dotnet#151]
When using the "raw" SDK methods like `OktaClient.Get` or `OktaClient.Post`, it seems that only the first level of an object graph is serialized: 

```csharp
await client.PostAsync("/api/v1/authn", new
    {
        username = "test3@example.com",
        password = "Changeme123!!",
        options = new
        {
            multiOptionalFactorEnroll = false,
            warnBeforePasswordExpired = false,
        }
    });
```

becomes

```json
{"username":"test3@example.com","password":"Changeme123!!","options":{}}
```

**Comment by laura-rodriguez** [comment]
The problem is not related to second-level properties but with bool properties in dynamic objects. Newtonsoft is not serializing them to JSON correctly.

**Comment by laura-rodriguez** [comment]
Add bool properties to the `UpdateUserProfileWithDynamicObject` integration test.
