### ISSUE TITLE
Possible String URL Encoding Issue

### ISSUE THREAD

**Issue by leebrandt** [okta/okta-sdk-dotnet#152]
oktaUser.Profile["custom-data"] = customData.ToString(Newtonsoft.Json.Formatting.None); 

await client.Users.UpdateUserAsync(oktaUser, idClaim.Value); 

With error: Okta.Sdk.OktaApiException: 'Api validation failed: userProfile'

**Comment by qnguyen12** [comment]
Error because there is no "custom-data" attribute in the user's profile

**Comment by nbarbettini** [comment]
@laura-rodriguez  Integration test case:
1. Create an anonymous .NET object with some properties/data
2. Serialize this data to a string using JSON.NET
3. This should not fail
