### ISSUE TITLE
Are there plans to implement other APIs?

### ISSUE THREAD

**Issue by bromanko** [okta/okta-sdk-dotnet#153]
The Okta API includes [endpoints for managing apps](https://developer.okta.com/docs/api/resources/apps.html) and assignments. Are there plans to add these endpoints to the SDK? Would you accept pull requests for this functionality?

**Comment by nbarbettini** [comment]
Yes, we're planning to add all of the management APIs to this SDK. For this first release, we decided to stick to just the Users and Groups APIs to ship it early and validate that the design of the SDK was on the right track. All the other APIs are on the roadmap, most likely starting with the Factors API.

Pull requests are always welcome. 😄

**Comment by bromanko** [comment]
Thanks. I'll only need a few actions but I'll see about adding it.

**Comment by bromanko** [comment]
Hmm. I looked a bit deeper and am not sure whether I can contribute. From my investigations, the model templates are sourced from the [@okta/openapi](https://www.npmjs.com/package/@okta/openapi) Node module. However, the source for this repo is not public. I wouldn't be able to add those models to spec.json.

**Comment by nbarbettini** [comment]
Good point. We can leave this issue open and I'll bring it up with the team.

**Comment by nbarbettini** [comment]
@bromanko Just curious, what are you missing here? The Apps API only?

**Comment by bromanko** [comment]
Yes. That was the only API I was looking to use right now. Specifically assigning users to applications.

**Comment by nbarbettini** [comment]
Looks like the Factors API is next up. Not sure yet when the Apps API will be added, but it'll be one of the next. Sorry that you can't contribute due to the way the "transport layer" part of the code is being generated.

**Comment by nbarbettini** [comment]
That being said, you should be able to work around it (if you haven't already) with the client's `Get` and `Post` methods. For example, for something like [this endpoint](https://developer.okta.com/docs/api/resources/apps.html#assign-user-to-application-for-sso),

```csharp
var userId = "auserid";
var appId = "anappid";
await client.PostAsync($"/api/v1/apps/{appId}/users", new { id = userId, scope = "USER" });
```

This isn't quite as nice as a built-in method, but it's better than rolling your own HttpClient. Hope that helps for now!
