### ISSUE TITLE
Throttling Controls

### ISSUE THREAD

**Issue by shoorik** [okta/okta-sdk-dotnet#156]
Per [Okta's rate-limiting recommendations](https://developer.okta.com/docs/api/getting_started/design_principles#rate-limiting), it would be nice if there was a mechanism for the caller to define behavior when Okta SDK nears or runs afoul of the limit.

Perhaps the caller could set a configuration option `OverRateLimitBehavior` (when the response status code is 429), with possible values of `PauseAndRetry` (default) or `Fail`. The `PauseAndRetry` option would sleep until `X-Rate-Limit-Reset` and repeat the request.

For cases where the caller is nearing the limit, perhaps they could set an option of `RateLimitRemainingMin` which would pause until `X-Rate-Limit-Reset` if the `X-Rate-Limit-Remaining` falls below the "floor" to prevent "Rate limit warning" from being logged to sys log.

At the very least, if the pause behavior is not implemented, perhaps the helper methods from different `*Client` classes could expose the `X-Rate-Limit-*` headers in some sort of a statistics class attached to result objects, so that callers could have a chance to rate-limit themselves, without punting to the low-level Get/Put/Post methods..

**Comment by nbarbettini** [comment]
Thanks for your suggestions (and your patience) @shoorik!

I agree that the SDK should make this easy to handle. I think the first pass will be automatically retrying, and future passes can add configuration. I'll track changes in this issue.

**Comment by mbegan** [comment]
@nbarbettini very interested in the approach taken, I have need to incorporate in other integrations.

For reference (no laughing please) this is what I did to back-off and avoid rate limit exhaustion
https://github.com/mbegan/Okta-PSModule/blob/master/Okta.psm1#L272

**Comment by nbarbettini** [comment]
FYI - we are planning on working on this in the near future. Stay tuned here 👍

**Comment by agiles231** [comment]
I have written a solution called proktasy that acts a proxy between Okta REST API clients and Okta. It is easily deployed using Tomcat and resolves all rate limiting issues. Also, an SDK would have a difficult time accounting for rate limiting produced by other applications, even if using the same SDK. proktasy solves that too.

**Comment by laura-rodriguez** [comment]
Hi Everyone 😄 ! We already provide a way to handle rate limit scenarios. Check out the readme for more info: https://github.com/okta/okta-sdk-dotnet#rate-limiting.
