### ISSUE TITLE
Add GetCollection to base client

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-dotnet#157]
The `GetAsync`, `PostAsync`, etc. methods on `OktaClient` can be used to retrieve any object from the Okta API, even if the SDK doesn't natively support it yet. However, there's no similar way to access a collection.

The base client should have a `GetCollection<T>` method that returns `IAsyncEnumerable<T>`.

**Comment by keronsen** [comment]
We would love to see this added, as it would allow us to use more of your API. (Apps API in our case.) Any chance of the pull request being merged into a release soon?

**Comment by nbarbettini** [comment]
@keronsen Yep, sorry for the delay! I'll get this merged ASAP.

**Comment by nbarbettini** [comment]
I've merged https://github.com/okta/okta-sdk-dotnet/pull/158 and it will be published as alpha6 on NuGet soon.

**Comment by nbarbettini** [comment]
@keronsen Published as [Okta.Sdk 1.0.0-alpha6](https://www.nuget.org/packages/Okta.Sdk/1.0.0-alpha6). Sorry for the delay! Let me know if it works for you, or if you have any other feedback.
