### ISSUE TITLE
StringEnum GetHashCode should use case-insensitive comparison

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-dotnet#164]
The Equals method in `StringEnum` uses a case-insensitive comparison: https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/StringEnum.cs#L87

But the GetHashCode method does not: https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/StringEnum.cs#L93

This could potentially cause problems if you're storing StringEnums in a dictionary or another structure that uses GetHashCode.

As noted by [this SO answer](https://stackoverflow.com/a/11476024/3191599), `ToLowerInvariant().GetHashCode` is one option, and using `InvariantIgnoreCase` in `Equals` is another option.

**Comment by nbarbettini** [comment]
`StringEnum` should probably implement `IEquatable<StringEnum>` too.

**Comment by laura-rodriguez** [comment]
Test case:

```csharp
var active1 = UserStatus.Active; // ACTIVE
var active2 = new UserStatus("Active");

// This already works:
(active1 == active2).Should().BeTrue();

// This does not:
active1.GetHashCode().Should().Be(active2.GetHashCode());
```
