### ISSUE TITLE
.net 4.6 /4.6.1 initialize new OktaClient => platform is not supported

### ISSUE THREAD

**Issue by MrZakos** [okta/okta-sdk-dotnet#169]
tried all sdk versions :
1.0.0-alpha4 (current version) 
1.0.0-alpha3 
1.0.0-alpha2 
1.0.0-alpha1
UPDATE
created new project and worked

**Comment by nbarbettini** [comment]
Just curious - what platform and version of Visual Studio or dotnet was this?

**Comment by MrZakos** [comment]
Windows 10 (1709)
Visual Studio 2017 Enterprise(15.5.2)
(I still try to figure our why my project throwing this error and new project doesn't)

**Comment by nbarbettini** [comment]
That is weird. Okta.Sdk targets .NET Standard 1.3, so it should be compatible with .NET 4.6 and up: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Since it worked on a new project, I'm assuming you have the .NET Core SDK installed?

**Comment by MrZakos** [comment]
Yes ,NET Core SDK is installed ,I tried it on both new project of .net core and .net 4.6.1 and worked

**Comment by nbarbettini** [comment]
Strange. If you are able to reproduce the problem reliably, let me know.

**Comment by nbarbettini** [comment]
Update - I found the real issue and fixed it in 1.0.0-alpha5. See the discussion in #172.
