### ISSUE TITLE
AddSmsFactorOptions does not work

### ISSUE THREAD

**Issue by samgithub-duplicate** [okta/okta-sdk-dotnet#186]
Following the example in this github document, The **CreateUserAsync** works BUT adding an SMS factor to the new user (vader) does not work.

var vader = await client.Users.CreateUserAsync(
    // User with password
    new CreateUserWithPasswordOptions
    {
        // User profile object
        Profile = new UserProfile
        {
            FirstName = "Myfirstname",
            LastName = "Mylastname",
            Email = "darth.father@myorg.com",
            Login = "darth.father@myorg.com",
        },
        Password = "D1sturB1ng!",
        Activate = false,
    });

///******** below does not work
   AddSmsFactorOptions addSmsFactorOptions = new AddSmsFactorOptions()
            {
                PhoneNumber = "+1 320-111-1234"                
            };

            var responseNew = await vader.AddFactorAsync(addSmsFactorOptions);

NOTE: There are NO errors.  The user is created in the okta dashboard directory -- but there are no factors. 

Signing in as this user thru a external app using OIDC, prompts for MFA setup.
Also NOTE:  I get a text verification code on my phone.   I tried it with Activate = true.  That also does not work.

Business Case:
If an organization wants users to use ONLY their business-supplied phones, they'll need to be able to control/pre-set the SMS phone, so the user is not responsible for setting it.

**Comment by nbarbettini** [comment]
Hey @samgithub-duplicate, I'll make sure the team looks at this soon.

Just to confirm, you are creating the user first (and the user is visible in the Okta dashboard) and then trying to add the factor?

**Comment by samgithub-duplicate** [comment]
I am creating the user, and adding the SMS factor after the user is created (as in the code above).  That approach did not work.

So I tried adding
 var newUser = await _oktaClient.Users.GetUserAsync(userID);
AFTER creating the user and  BEFORE adding the SMS factor.  The 'newUser' object is returned correctly.

Even with this approach, the AddSmsFactorOptions  does not work.  
The user does get created and exists in the OKTA dashboard.

BTW:  I'll be happy to test this for you, once your team has fixed it.

**Comment by samgithub-duplicate** [comment]
@nbarbettini 
@laura-rodriguez 
Are there any updates on this?

**Comment by laura-rodriguez** [comment]
Hi @samgithub-duplicate ! I haven't had the chance to review this yet. But it is at the top of my backlog for the next days. Sorry about it.

**Comment by laura-rodriguez** [comment]
Hi @samgithub-duplicate, I have just tried below test code block and I was able to successfully validate that the factor was added for the new user with the status `PENDING_ACTIVATION`.
So I wonder if it could be because of your Okta Org configuration. Could you please tell me how did you configure your Org/App for MFA?

```
...
var profile = new UserProfile
            {
                FirstName = "Jill",
                LastName = "Factor-SMS",
                Email = "jill-factor-securityquestion@example.com",
                Login = "jill-factor-securityquestion@example.com",
            };

            var createdUser = await client.Users.CreateUserAsync(new CreateUserWithPasswordOptions
            {
                Profile = profile,
                Password = "Abcd1234",
            });

            try
            {
                await createdUser.AddFactorAsync(new AddSmsFactorOptions()
                {
                    PhoneNumber = "+1416835xxxx",
                });

                var factors = await createdUser.ListFactors().ToArray();
                factors.Count().Should().Be(1);

                var smsFactor = await createdUser.ListFactors().OfType<ISmsFactor>().FirstOrDefault();
                smsFactor.Should().NotBeNull();
                smsFactor.Profile.PhoneNumber.Should().Be("+1416835xxxx");
```

**Comment by samgithub-duplicate** [comment]
I'll check it with using similar approach as your code and see if I can get it to work.  What version of OKTA.SDK are you using??

**Comment by laura-rodriguez** [comment]
I am using v1.0.0-alpha6, the latest one.

**Comment by laura-rodriguez** [comment]
I am going to close this issue because of the lack of response. If you face this issue again feel free to reopen it. Thanks!
