### ISSUE TITLE
@nbarbettini Issue #186

### ISSUE THREAD

**Issue by samgithub-duplicate** [okta/okta-sdk-dotnet#189]
nbarbettini:

Can you please respond to issue #186?

I just need to know if 
a) the SMSFactor component in the SDK  has been implemented, if not is it on the timeline (approx when)?
b) Am I doing something wrong?

Thanks

**Comment by nbarbettini** [comment]
Hey @samgithub-duplicate, sorry for the delay. Closing this so we can discuss in one place: #186
