### ISSUE TITLE
Missing post_logout_redirect_uris in OpenIdConnectApplication

### ISSUE THREAD

**Issue by laura-rodriguez** [okta/okta-sdk-dotnet#209]
The post_logout_redirect_uris array property is missing on POST /api/v1/apps for an OAuth 2.0 app. See the request example here:
https://developer.okta.com/docs/api/resources/apps#add-oauth-20-client-application

Related: https://github.com/okta/openapi/issues/128

**Comment by brandonam** [comment]
Is there any updates to this or perhaps a work around without having to interact with the API directly through an httpClient?
