### ISSUE TITLE
Factors have Id property set to null

### ISSUE THREAD

**Issue by neilgallagher** [okta/okta-sdk-dotnet#22]
Hello Im using version 3.1 of the c sharp cleint. 

Im using  

var allFactors = factorsClient.GetFactorCatalog();

which works but all the **Id** properties are null. Without the **Id** property the challenge Apis calls return an error

Hope you can help

Thanks

**Comment by bigtang1** [comment]
The issue is the Constants.CatalogEndpoint at the end of the GetFactoCatalog call - removing that returns Factors that have Ids - not sure why it is there however.

        public virtual List<Factor> GetFactorCatalog()
        {
            var response = BaseClient.Get(resourcePath + Constants.CatalogEndpoint);
            return Utils.Deserialize<List<Factor>>(response);
        }

**Comment by jokecamp** [comment]
Fix: Instead of querying for the catalog you can get the page results directly like so:

```
  var userFactorsClient = okta.GetUserFactorsClient(user);
  var list = userFactorsClient.GetList(null, 20);
  var factors = list?.Results;
```

That will have a valid factor.id
