### ISSUE TITLE
System.OktaApiException Api validation failed: login

### ISSUE THREAD

**Issue by jakehockey10** [okta/okta-sdk-dotnet#224]
I'm having an issue that came up in the last few days and I'm not sure how to determine what the issue is.  We are pulling in the 1.0.0-alpha3 NuGet package, which has been working great for us until now.  We create our `OktaClient` like this: 

``` C#
 public class OktaApi
    {
        #region Constructors

        public OktaApi(string url, string token) => Client = new OktaClient(
            new OktaClientConfiguration
            {
                OrgUrl = url,
                Token = token
            });

        #endregion
...
```

But we get the exception when calling this method:

``` C#

        #region Public Methods

        public async Task<IUser> CreateUserAsync(string emailId, string firstName, string lastName,
            bool activate = false) => await Client.Users.CreateUserAsync(
            new CreateUserWithoutCredentialsOptions
            {
                Profile = new UserProfile
                {
                    FirstName = firstName,
                    LastName = lastName,
                    Email = emailId,
                    Login = emailId
                },
                Activate = activate
            });

```

At first, I thought our API token was somehow different than it used to be and since I can't see what it is after creation in the Okta Admin Portal, I created a new one and tried using that instead.  I still got the same error with the brand new token I created.

Our organization url is correct as well, and has changed in our code in a very long time.  One thing I was wondering was if I need to use the organization url like `teamdigital.oktapreview.com` or if I need to give the full url to the authorization server.  I figured this wasn't necessary as it wasn't necessary for a long time and I only started seeing this issue a few days ago.

Could I get some help getting pointed in the right direction?  Thanks!

**Comment by laura-rodriguez** [comment]
Hi @jakehockey10! Your `OrgUrl` should be something like this: `https://teamdigital.oktapreview.com/`.
Have you checked the `ErrorCauses` of your exception to look for more details?  
What I also suggest to you is trying with postman. We provide a users collection ready to use: https://developer.okta.com/docs/api/resources/users#getting-started, you just have to configure your `API token` and `OrgUrl`. You can test [your request](https://developer.okta.com/docs/api/resources/users#create-user-without-credentials) faster and discard possible scenarios.

**Comment by jakehockey10** [comment]
our `OrgUrl` is `https://teamdigital.oktapreview.com/` so that looks good to me.  Where can I check the `ErrorCauses`?

I'll try this in postman, but I get pretty quick feedback because we wrote some automated tests that we don't run on a schedule, but can run to exercise the endpoints we are using.

**Comment by jakehockey10** [comment]
@laura-rodriguez I am trying the endpoints in postman.  I'm attempting to get a single user that is my account with the following url: `https://teamdigital.oktapreview.com/api/v1/users/j.smith@questintegrity.com`

I'm also exercising the create user without credentials endpoint and that works just fine.  So it seems to be an issue with the way i'm using the SDK.  But the way I'm using the SDK hasn't changed from when it was working to now.  I'm not sure what the issue is...

**Comment by laura-rodriguez** [comment]
@jakehockey10  I've tried to reproduce this issue with `1.0.0-alpha3` but it works fine, even in the latest versions.
To check `ErrorCauses` debug your code when the `Exception` is thrown and inspect the exception properties. You should be able to check these attributes:
```
  try
            {
                await client.GetAsync<Resource>("/something");
            }
            catch (OktaApiException apiException)
            {
                var expectedMessage = "Api validation failed (500, E0000001): Password requirements were not met., Another bad thing that happened";
                apiException.Message.Should().Be(expectedMessage);
                apiException.ToString().Should().StartWith($"Okta.Sdk.OktaApiException: {expectedMessage}");

                var causes = apiException.ErrorCauses.ToArray();
                causes.Should().HaveCount(2);
                causes.First().ErrorSummary.Should().Be("Password requirements were not met.");
                causes.Last().ErrorSummary.Should().Be("Another bad thing that happened");
            }
```
This piece of code was extracted from our unit tests, you can take a look at other scenarios here:
https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk.UnitTests/OktaClientShould.cs

Also, you can update your NuGet package to `1.0.0-alpha8`.

**Comment by jakehockey10** [comment]
@laura-rodriguez , Nuget manager in Visual Studio doesn't seem to be aware of `1.0.0-alpha8`, but I was able to update to 7, which then I was able to see the ErrorCauses property of the exception (3 didn't have that property).  I was able to resolve my issue.  It was not an issue with the sdk.

Thank you so much for your support!
