### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by justinhelgerson** [okta/okta-sdk-dotnet#229]
I might be interested in leveraging [e-mail verification](https://developer.okta.com/docs/api/resources/users#verify-email) from the Okta SDK.  I spoke with our account manager and we should be getting a flag set to enable the usage of the beta API resources.

If we pursue this, would you be open to me contributing to add this functionality?  I wanted to ask before investing some time exploring it.

**Comment by nbarbettini** [comment]
We add endpoints to this SDK (and all of our SDKs) by editing a shared OpenAPI spec file that all the SDKs consume and generate code from. That means that adding new endpoints is something only we can do right now, but it would be super helpful to describe your use case here so we can make sure it is covered when these endpoints get added.

In case you hadn't seen, you can use these generic methods to call any endpoint we haven't added to the SDK yet: https://github.com/okta/okta-sdk-dotnet#call-other-api-endpoints (Don't want you to be blocked in the mean time 🙂 )
