### ISSUE TITLE
Implement CreateUserInGroup in IUsersClient

### ISSUE THREAD

**Issue by laura-rodriguez** [okta/okta-sdk-dotnet#233]
We should support this use case: https://developer.okta.com/docs/api/resources/users#create-user-in-group

`groupIds` is not part of the user definition in the spec.
The issue is the update and response objects do NOT contain `groupIds`, so we cannot model it easily.

**Comment by craigsmitham** [comment]
We need this feature so that our integration that is owned by a group admin can create users for its group.

**Comment by laura-rodriguez** [comment]
Closing since this was fixed already. See [`CreateUserRequest`](https://github.com/okta/okta-sdk-dotnet/blob/1849eb0d2b199d3e3fc2723bb4dc732c7b135352/src/Okta.Sdk/Generated/CreateUserRequest.Generated.cs).
