### ISSUE TITLE
Provide access to raw requests/responses

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-dotnet#248]
From @ryannewington in #188:

> Alternatively, is there a way to log raw request/response data with the SDK? This would avoid having to do any certificate trickery at all.

**Comment by nbarbettini** [comment]
Background: This SDK is designed to hide a lot of the "raw" HTTP request/response complexity from the caller, and provide easy .NET methods and POCOs to use. This doesn't cover 100% of cases though, and there are times when a caller may want to get closer to the wire.

The `client.GetAsync/PostAsync` methods make it possible to construct requests manually, but there is no easy way to inspect the raw responses. We should consider adding an optional way to do that.

**Comment by bryanapellanes-okta** [comment]
Closing as "won't do" for now.  Anyone feel free to comment here if this is a desirable feature for you.
