### ISSUE TITLE
Query for user based on profile attribute value 

### ISSUE THREAD

**Issue by nemo5555** [okta/okta-sdk-dotnet#276]
I want to query for user matching a specific profile attribute value. Something like this:

var auser = client.Users.ListUsers(search: "filter=employeeNumber Eq 119859");
Console.WriteLine("User Found matching the query " + auser.Result.Profile.Login)

I am unable to achieve this. I am probably not using the search\filter expression correctly.
Please help.

**Comment by laura-rodriguez** [comment]
Hi @nemo5555,
The syntax doesn't look correct. If you want to use `filter` you should have something like this:
```
// Verify user exists in list of active users
var activeUsers = await client.Users.ListUsers(filter: "status eq \"ACTIVE\"").ToArray();
```
If you want to use `search`:
```
 var foundUsers = await client.Users
                        .ListUsers(search: $"profile.nickName eq \"{createdUser.Profile.GetProperty<string>("nickName")}\"")
                        .ToArray();
```
Let me know if this works for you so we can close the issue :)

**Comment by nemo5555** [comment]
Hi @laura-rodriguez ,

Thanks for looking into this issue.
First thing, I think I am having some SDK or .NET problems in my code. The 'await' operator has never worked for me with the OKTA SDK. When I use it in my code, Visual Studio says this -
"The 'await' operator can only be used within an async method. Consider making this method with the 'async' modifier and changing its return type to task.

If I remove the 'await' I don't get a .ToArray() method for ListUsers. What am I missing here ?. I have been only able to make the code work like below to get a user's profile attributes:
(I am a .NET beginner and started with .NET Core 2.0 console apps. Thanks :))

static void Main(string[] args)
        {
            Console.WriteLine("Hello OKTA Admin!");
            var client = new OktaClient(new OktaClientConfiguration
            {
                OktaDomain = "https://myorg.okta.com",
                Token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            });

            var auser = client.Users.GetUserAsync("oktauser@oath.com");

            Console.WriteLine("Username = " + auser.Result.Profile.Login);
            Console.WriteLine("Id = " + auser.Result.Id);
            Console.WriteLine("Email = " + auser.Result.Profile.Email);
            var aprofile = auser.Result.Profile;
            foreach (var item in aprofile.GetData())
            {
                if (item.Key == "employeeNumber")
                {
                    Console.WriteLine("employeeNumber= " + item.Value);
                }

            }
}

**Comment by laura-rodriguez** [comment]
@nemo5555 what version of the SDK are you using?

**Comment by nemo5555** [comment]
Looks like it is Okta.Sdk (1.0.0) . I Nuget it few days back.

**Comment by laura-rodriguez** [comment]
@nemo5555 I am curious about what could be wrong. If you have your test sample in GitHub I would be happy to take a look.

**Comment by nemo5555** [comment]
@laura-rodriguez Here's the gist. It's pretty much what I provided above. And this works for me without using the "await" operator. But I want to do LINQ-like queries based on profile attribute values which I am not able to do.
Thanks again for your time on this.

**Comment by nemo5555** [comment]
@laura-rodriguez sorry about that. Here's it is:

https://gist.github.com/nemo5555/eec04a9d475cf408267a5c1e62e72252

**Comment by laura-rodriguez** [comment]
Hey @nemo5555,

Visual Studio is complaining because, as you are using async callbacks, is expecting the `Main` method to be declared as `async Task`.

I recommend you to take a look at https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/.

Also, here you can find a working gist: https://gist.github.com/laura-rodriguez/e655d6cacf66fb68402d4366710375c8

Happy coding!

**Comment by nemo5555** [comment]
Hi @laura-rodriguez ,

Thanks for your valuable suggestions and the ref gist. 
I modified my code as per your gist (https://gist.github.com/nemo5555/eec04a9d475cf408267a5c1e62e72252).

And I am still getting a warning on "Program.OktaTasksAsync(client)" in VS2017 saying 

"Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call"

While I am still trying to get a handle on 'Async' and 'await' by reading the MS article, it would be great if you can advise on this warning as well.

Thanks !!

**Comment by nemo5555** [comment]
Hi @laura-rodriguez ,

I was finally able to get my head around Async programming and after some reading I was able to fix my code. Here's my updated code which works flawless now: https://gist.github.com/nemo5555/eec04a9d475cf408267a5c1e62e72252

**Comment by nemo5555** [comment]
Hey @laura-rodriguez ,
Now that all that is sorted out, I would need some help with making a correct "search expression" to find any user (active or inactive) by email. Right now I can do a query by "Email" using "q: email" but looks like that only looks for active users. To look for inactive (deprovisioned) users as well, I had to first use the below filter expression:

var foundinactiveuser = await client.Users.ListUsers(filter: "status eq \"DEPROVISIONED\"").ToArray();

and then iterating every element in foundinactiveuser.Result via foreach loop. This takes long time.
Hence, I was hoping either to be able to use a LINQ-like query or a proper "search expression" to find inactive user by email.

Any ideas or suggestions ?
Thanks !!

**Comment by nbarbettini** [comment]
@nemo5555 Try this:

    var user = await client.Users.ListUsers(filter: "profile.email eq \"email@example.com\"").FirstOrDefault();

This will find the user with `email@example.com`, regardless of whether they are active or deprovisioned. If there is no user with that email, it will return `null`.

**Comment by nemo5555** [comment]
Thanks @nbarbettini and @laura-rodriguez for all your suggestions and help. I was able to do something like this and it works for me.

public static async Task<IUser[]> SearchOktaUserByEmailAsync(IOktaClient client, string emailid)
        {
            var afounduser = await client.Users.ListUsers(search: $"profile.email eq \"{emailid}\"").ToArray();
            return afounduser;
        }

I think we can close this issue now.
