### ISSUE TITLE
AmbiguousMatchException: Multiple custom attributes of the same type found

### ISSUE THREAD

**Issue by justinhelgerson** [okta/okta-sdk-dotnet#296]
I'm experiencing a runtime issue with this library and I was hoping someone might be able to provide some guidance.  It looks to be caused by [this line](https://github.com/okta/okta-sdk-dotnet/blob/e155419fe2097b0bc490e366e182d173526b58ac/src/Okta.Sdk/Internal/UserAgentBuilder.cs#L44) in the `UserAgentBuilder` class.  I'm running an ASP.NET (not Core) application on .NET Framework.  The runtime exception isn't an issue when running on .NET Core.

I'm not able to reproduce the issue on my Windows 10 machine, but in our test & production environments (Windows Server 2012) we do experience the runtime exception.  I tried bumping up the version of .NET Framework on our test server (to match my development environment), but no dice.

I realize this isn't exactly an issue with the Okta library and it's likely a netstandard vs netframework topic, but I suspect someone else may run into this issue as well.  I've already downgraded one application to the older `Okta.Core.Client` library to address this issue.  I'd like to keep using this library, and unfortunately the issue is caused by the user agent telemetry data being collected which isn't relevant to what I'm trying to do. 

```
System.Reflection.AmbiguousMatchException: Multiple custom attributes of the same type found.
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Runtime.InteropServices.RuntimeInformation.get_FrameworkDescription()
   at Okta.Sdk.Internal.UserAgentBuilder.Generate()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
```

**Comment by laura-rodriguez** [comment]
Hi @justinhelgerson,
Sorry for the inconvenience. 
Are you experiencing this issue with both the ASP.NET SDK and the Okta management SDK?
Can you tell me the version of the SDK's you are using?

**Comment by justinhelgerson** [comment]
I'm experiencing this with the `Okta.Sdk` package in both versions 1.1.0 and 1.2.0.

**Comment by nbarbettini** [comment]
I bet it is related to: https://github.com/Azure/autorest/issues/1542

That thread seems to imply that disabling or updating Application Insights solves the problem, but regardless of that - @laura-rodriguez I think we should add some extra checks to the user agent builder so that if any part of the telemetry code fails, it doesn't cause a fatal error. It's better for us to send no telemetry than blow up the application.

**Comment by justinhelgerson** [comment]
@nbarbettini That would be a welcome change.  I definitely understand the desire for that type of data, but I think foregoing it and letting the Okta operation succeed could be a good change.

I read through that thread as well.  We're not using Azure or Application Insights.  I've been stumped trying to track down the issue since early this morning, unfortunately no progress.

**Comment by laura-rodriguez** [comment]
Agree with you @nbarbettini.
Regardless it seems to be an external issue; we need to cover any fail in the agent builder to avoid fatal errors.

Thanks for bringing this up @justinhelgerson!

**Comment by nbarbettini** [comment]
@justinhelgerson PRs are definitely welcome! (You'd need to sign our [CLA](https://developer.okta.com/cla/) if you haven't already)

Regardless of who works on it, some try/catches around the critical code should do it. I'd like to see the UserAgentBuilder resilient enough that even if any of the string manipulation fails (for some reason), it will simply return an empty string or the bare minimum info it has.

**Comment by justinhelgerson** [comment]
@nbarbettini Any idea when you'll be pushing an updated NuGet package?

**Comment by laura-rodriguez** [comment]
Hi @justinhelgerson, thanks for your contribution 🎉 .
We will be working on a minor internal task these days and, we want to include it as part of the same patch. 
We are expecting to publish an updated NuGet package by the end of next week.

**Comment by justinhelgerson** [comment]
Awesome. Thanks Laura!

**Comment by laura-rodriguez** [comment]
Hi @justinhelgerson, your contribution is on NuGet 🎉
