### ISSUE TITLE
Ensure that the HttpClient switches to the new server when DNS is updated for a failover

### ISSUE THREAD

**Issue by laura-rodriguez** [okta/okta-sdk-dotnet#303]
See: 
* https://github.com/dotnet/corefx/issues/11224
* https://github.com/okta/okta-sdk-dotnet/pull/300

**Comment by bryanapellanes-okta** [comment]
@laura-rodriguez Is there additional action needed to resolve this?

**Comment by bryanapellanes-okta** [comment]
Closing for now. Won't do.
