### ISSUE TITLE
Add support for SMS Auto-Activate

### ISSUE THREAD

**Issue by deano-au** [okta/okta-sdk-dotnet#309]
Add support for SMS Auto-Activate as per:
[https://developer.okta.com/docs/api/resources/factors#enroll-and-auto-activate-okta-sms-factor](https://developer.okta.com/docs/api/resources/factors#enroll-and-auto-activate-okta-sms-factor)

**Comment by laura-rodriguez** [comment]
Hi @deano-au,

Sorry for the late response. We already support this use case, you have to use the following code:

```
 await user.AddFactorAsync(new AddSmsFactorOptions()
                {
                    PhoneNumber = "{userPhoneNumber}",
                });
```
I've created an[ integration test](https://github.com/okta/okta-sdk-dotnet/pull/317/files#diff-29df9fc0b58f5d24b8b8a11b7684ab54R62.) to make sure that this is working properly, you can check out there as well. 
Let me know if this helps. Thanks!
