### ISSUE TITLE
Add More Details to User

### ISSUE THREAD

**Issue by theBrendeny** [okta/okta-sdk-dotnet#322]
In the Okta API (using Postman), I've noticed there are a lot more details when searching a user than it shows in PowerShell. Will the full user details from Okta API be implemented?

**Comment by laura-rodriguez** [comment]
Hi @theBrendeny ,
I want to double check a few things:
* What Powershell client are you using? 
* What are those details that are not part of the Okta API?

**Comment by theBrendeny** [comment]
PowerShell version 5.1.17763.592

Example data has been removed for privacy reasons, etc.

Example:
$user = Get-OktaUser -id <id>

Output ($user.Profile):

```
Login          : 
Email          : 
FirstName      : 
LastName       : 
MobilePhone    :
SecondaryEmail :
```

Get-OktaUser "Profile" attribute only shows those 6 fields. In the API I'm using (Postman), we are able to retrieve much more. These are all the fields we can see:

```
    "profile": {
        "lastName": "",
        "zipCode": ",
        "preferredLanguage": "",
        "manager": "",
        "city": "Sydney",
        "nickName": "",
        "displayName": "",
        "timezone": "",
        "secondEmail": "",
        "honorificPrefix": "",
        "title": "",
        "locale": "",
        "login": "",
        "firstName": "",
        "mobilePhone": "",
        "streetAddress": "",
        "countryCode": "",
        "organization": "",
        "userType": "",
        "state": "",
        "email": "",
        "sapId": ""
    },
```

Thank you for your response.

**Comment by laura-rodriguez** [comment]
Hi @theBrendeny ,

We're planning to mark the PowerShell package as deprecated soon, so there's not any plan to extend this package functionality.

**Comment by gabrielsroka** [comment]
Hi @theBrendeny ,

I have an unofficial PowerShell module I've written:
https://github.com/gabrielsroka/OktaAPI.psm1

It provides everything you see in Postman.
