### ISSUE TITLE
Post logout redirect URIs are not accessible from OpenIdConnectApplicationSettings object

### ISSUE THREAD

**Issue by brandonam** [okta/okta-sdk-dotnet#326]
I'm attempting to update an Application object of type OpenIdConnectApplication.

However it seems that the Post Logout Redirect URI's property array is not accessible

![image](https://user-images.githubusercontent.com/1925792/61386877-5891ae00-a8b5-11e9-9b03-2397ea4038f9.png)

Is this by design? I'm not sure if this is related to #209 please close if it is.

**Comment by laura-rodriguez** [comment]
Hi @brandonam ,

As you mentioned this is related to #209. 
We auto-generates part of our code via an openapi spec. We need to review the spec to check why this property is not being added to the code.

What you can do in the meantime is the following:

```
var retrieved = await client.Applications.GetApplicationAsync<IOpenIdConnectApplication>(createdApp.Id);
retrieved.Settings.OAuthClient.SetProperty("post_logout_redirect_uris", new List<string>(){ "https://example.com/oauth2/postLogoutRedirectUri" });
await client.Applications.UpdateApplicationAsync(retrieved, retrieved.Id);
```
Most of the classes inherit from `Resource` which allow you to add dynamic values. 
I hope this helps.

**Comment by laura-rodriguez** [comment]
Related to #209.
