### ISSUE TITLE
Can't use GetAsync to Return a List

### ISSUE THREAD

**Issue by mattmcnabb** [okta/okta-sdk-dotnet#329]
I'm trying:

```csharp
client.GetAsync<List<Application>>(
    href: string.Format("/api/v1/apps?filter=user.id eq \"{0}\"&expand=user/{0}", User.Id)
).ToList()
```

But I get a compile error on this:

`System.Threading.Tasks.Task<List<Application>> OktaClient.GetAsync<List<Application>>(string href, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
The type 'System.Collections.Generic.List<Okta.Sdk.Application>' cannot be used as type parameter 'T' in the generic type or method 'OktaClient.GetAsync<T>(string, CancellationToken)'. There is no implicit reference conversion from 'System.Collections.Generic.List<Okta.Sdk.Application>' to 'Okta.Sdk.Resource'. (CS0311) [Okta.PS]`

And if I try `[T]` instead of `List[T]` then I get a runtime error:

```
{Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 
'System.Collections.Generic.IDictionary`2[System.String,System.Object]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.     
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection  
interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to
deserialize from a JSON array.
Path '', line 1, position 1.
 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object 
existingValue, String id)
 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, 
JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
 at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
 at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
 at Okta.Sdk.Internal.DefaultSerializer.Deserialize[T](String input)
 at Okta.Sdk.Internal.DefaultSerializer.Deserialize(String json)
 at Okta.Sdk.Internal.DefaultDataStore.GetAsync[T](HttpRequest request, RequestContext requestContext, CancellationToken cancellationToken)
 at Okta.Sdk.OktaClient.GetAsync[T](HttpRequest request, CancellationToken cancellationToken)}
```

Any thoughts on how to retrieve a list from an arbitrary endpoint? Thanks!

**Comment by laura-rodriguez** [comment]
Hi @mattmcnabb ,
Have you tried to make this request in Postman for example?
It can help us to determine if it's an SDK or API issue/restriction.

**Comment by mattmcnabb** [comment]
@laura-rodriguez I've run it in PowerShell after using the curl example [here](https://developer.okta.com/docs/reference/api/apps/#request-example-13). 

![image](https://user-images.githubusercontent.com/6998507/61565507-3b8ce480-aa47-11e9-8253-61bfbde051c2.png)

**Comment by laura-rodriguez** [comment]
Hi @mattmcnabb ,

You can try the [ListApplications](https://github.com/okta/okta-sdk-dotnet/blob/79156f1a8652f5b4327ac0609570e9f125fc347a/src/Okta.Sdk/Generated/ApplicationsClient.Generated.cs#L32) method. 
It should look like this:
```
var appList = await client.Applications.ListApplications(filter: "user.id eq \"{yourUserId}\"", expand: "user/{yourUserId}").ToArray();
```

**Comment by mattmcnabb** [comment]
@laura-rodriguez Thanks, that definitely helps me retrieve applications assigned to a user. However, I don't think this solves the larger question which is how to use the GetAsync method to make arbitrary API calls that return a list. This doesn't seem possible unless I'm missing something, and I think this will be required to call resource types that aren't currently supported by the API client.

**Comment by laura-rodriguez** [comment]
@mattmcnabb if you want to get a list then you'll to use the `GetCollection<T>` method. Here you can see an example of how we use it to get a list of Applications: https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Generated/ApplicationsClient.Generated.cs#L33
