### ISSUE TITLE
System.FormatException: String '' was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by ryannewington** [okta/okta-sdk-dotnet#330]
When a resource has a DateTime attribute that is a 'empty string' as opposed to NULL, the Sdk throws a System.Format exception on line 263 of Resource.cs.

```cs
        protected DateTimeOffset? GetDateTimeProperty(string name)
        {
            var raw = GetStringProperty(name);
            if (raw == null)
            {
                return null;
            }

            // Exception throw here
            return DateTimeOffset.Parse(raw);
        }
```

A possible solution could be to use string.IsNullOrEmpty in the null check

```cs
        protected DateTimeOffset? GetDateTimeProperty(string name)
        {
            var raw = GetStringProperty(name);
            if (string.IsNullOrEmpty(raw))
            {
                return null;
            }

            return DateTimeOffset.Parse(raw);
        }
```

I'm not sure of the exact cause of resources in Okta ending up with empty strings in these attributes, but I think NULL and empty string should be treated in the same manner when parsing a response in the SDK.

The alternative is dealing this in the downstream code on every line to unwrap a date time with something ugly like

```cs
info.ConsumedCodeDate = string.IsNullOrEmpty(profile.GetProperty<string>("consumedCodeDate")) ? null : profile.GetProperty<DateTimeOffset?>("consumedCodeDate")?.DateTime;
```

**Comment by laura-rodriguez** [comment]
Hi @ryannewington ,

What is the Resource that is getting this issue, is it `User`? 
Also, do you know if the property is a custom attribute or a predefined one?

**Comment by ryannewington** [comment]
Hi Laura!

It is indeed a user with a custom attribute.

I think when you clear the date value using the okta profile editor, it replaces it with an empty string, causing the sdk to fail.

Ryan

**Comment by laura-rodriguez** [comment]
@ryannewington thanks for the info! You can use a workaround for this case by treating custom attributes date-formatted as strings: https://github.com/okta/okta-sdk-dotnet#json-serialization.

Let me know if it helps you in the meantime.

**Comment by ryannewington** [comment]
@laura-rodriguez, thanks I'll keep that in mind for future implementations. It seems like it could be useful in other situations too. I have my workaround for now, as I do actually need them as datetime values. I just wanted to highlight the 'incompatibility' with a default behaviour of the Okta web UI, and the assumption in the SDK that a datetime on a profile cannot be a blank string.

**Comment by ryannewington** [comment]
So this is not being fixed?

**Comment by laura-rodriguez** [comment]
doh! my bad, I confused this issue with another one related to DateTime serialization. The empty string check should be definitely fixed. Thanks for the heads up!

**Comment by ryannewington** [comment]
Happy to submit a PR if needed

**Comment by laura-rodriguez** [comment]
PRs are welcome ❤️
