### ISSUE TITLE
How to obtain a request's 'next' / 'after' key

### ISSUE THREAD

**Issue by JesseKlaasse** [okta/okta-sdk-dotnet#337]
I'm using the following endpoint to sort of proxy the Okta logging:

```
        public async Task<OktaLogModel> Get(
            [FromUri] string after = null,
            [FromUri] int limit = 100,
            [FromUri] string q = null,
            [FromUri] string filter = null,
            [FromUri] DateTimeOffset? since = null,
            [FromUri] DateTimeOffset? until = null,
            [FromUri] string sortOrder = null,
            CancellationToken cancellationToken = default)
        {
            var sinceStr = since?.ToString(OktaIsoDateStringFormat);
            var untilStr = until?.ToString(OktaIsoDateStringFormat);
            
            var logEvents = await _oktaClient.Logs
                .GetLogs(after: after, q: q, filter: filter, since: sinceStr, until: untilStr, sortOrder: sortOrder) // we don't use 'limit' here, since this is only the Okta (!) pagination limit - the SDK handles pagination itself, so our 'ToList' could need 5 requests for example
                .Take(limit) // this acts as our (!) pagination limit
                .ToList(cancellationToken);
            
            return new OktaLogModel
            {
                AfterKey = logEvents.Last().Uuid,
                LogEvents = logEvents
            };
        }
```

I'm currently setting the `AtfterKey` to the last `Uuid`, but actually I would need (a part of) the 'next' response header from the final request, which could be something like this:

```
Next: <https://tiptrack-dev.okta-emea.com/api/v1/logs?limit=1&after=1565011268973_1>; rel="next"
``` 

Is there a way to get this key?

For Groups and Users there is a (albeit very unelegant) solution, since I can use the last Group Id as AfterKey, and the last User id prefixed by a "0" for the User's AfterKey. I know it's ugly and not guaranteed to keep working, but it works for now. However, for Logs it's not possible, since the after key (`1565011268973_1`) in the example above can't be derived from the result itself.

**Comment by JesseKlaasse** [comment]
In the meantime, I have discovered the paged enumerator in the `ICollectionClient`. I have implemented it like this, and it seems to work now:

```
    public static class CollectionClientExtensions
    {
        public static async Task<OktaApiResponse<T>> ToListAsync<T>(this ICollectionClient<T> collectionClient, int limit, int? maxOktaLimit = null, CancellationToken cancellationToken = default)
            where T : IResource
        {
            var pagedEnumerator = collectionClient.GetPagedEnumerator();

            var oktaLimit = maxOktaLimit ?? limit;
            
            var items = new List<T>();
            WebLink next = null;

            while (items.Count < limit && await pagedEnumerator.MoveNextAsync(cancellationToken))
            {
                items.AddRange(pagedEnumerator.CurrentPage.Items.Take(limit - items.Count));
                next = pagedEnumerator.CurrentPage.NextLink;
            }

            string afterKey = null;

            if (next != null)
            {
                var myUri = new Uri(next.Target);
                afterKey = HttpUtility.ParseQueryString(myUri.Query).Get("after");
            }
                    
            return new OktaApiResponse<T>
            {
                AfterKey = afterKey ?? string.Empty,
                Items = items
            };
        }
    }
```

```
        public async Task<OktaApiResponse<ILogEvent>> Get(
            [FromUri] string after = null,
            [FromUri] int limit = 100,
            [FromUri] string q = null,
            [FromUri] string filter = null,
            [FromUri] DateTimeOffset? since = null,
            [FromUri] DateTimeOffset? until = null,
            [FromUri] string sortOrder = null,
            CancellationToken cancellationToken = default)
        {
            var sinceStr = since?.ToString(OktaIsoDateStringFormat);
            var untilStr = until?.ToString(OktaIsoDateStringFormat);

            var maxOktaLimit = Math.Min(limit, 1000);

            return await _oktaClient.Logs
                .GetLogs(after: after, limit: maxOktaLimit, q: q, filter: filter, since: sinceStr, until: untilStr, sortOrder: sortOrder)
                .ToListAsync(limit, maxOktaLimit, cancellationToken);
        }
```

**Comment by JesseKlaasse** [comment]
One strange side effect; I had to change the `while` condition to:

```
            while (items.Count < limit && await pagedEnumerator.MoveNextAsync(cancellationToken) && pagedEnumerator.CurrentPage != null && pagedEnumerator.CurrentPage.Items.Any())
```

Otherwise, I'm running into an infinite loop leading to an almost immediate rate limit violation. This seems to be caused by the fact that `pagedEnumerator.MoveNextAsync(cancellationToken)` seems to return `true` in cases where, in my opinion, it should be `false`. For example, when I ask for 1500 logs (which are Okta page limited to 1000 logs in one call), I get 1 response with 1000 events, then 1 response with 428 events, and after that, endless responses with 0 events. I'm puzzled.

**Comment by aperlstein** [comment]
Any ideas when this is going to get looked at?  I am running into the same problem.

**Comment by laura-rodriguez** [comment]
Hi @aperlstein ,

Thanks for bringing this up to our attention!

Can you please describe what you are trying to do and post a minimal code sample?

**Comment by aperlstein** [comment]
Same issue that the user above is / was having:

`_client.Logs.GetLogs(limit: 1).ToListAsync(); //Infinite Loop`

**Comment by laura-rodriguez** [comment]
Hi @aperlstein,

I just checked with the corresponding team, and this is expected for the Logs API. This is because this is an infinite stream. You can check out for more details [here](https://developer.okta.com/docs/reference/api/system-log/#polling-requests).

So, if you want a finite number of pages, you can either use [Bounded Queries](https://developer.okta.com/docs/reference/api/system-log/#bounded-requests) or do something like this:

```
    var retrievedLogs = new List<ILogEvent>();
    var logs = client.Logs.GetLogs(limit: 10, since: "2020-07-28");
    var enumerator = logs.GetPagedEnumerator();

    while (await enumerator.MoveNextAsync() && enumerator.CurrentPage.Items.Any())
    {
         retrievedLogs.AddRange(enumerator.CurrentPage.Items);
     }
```

I hope this helps.

**Comment by aperlstein** [comment]
Very helpful.  Apologies, I should have read the REST API documentation more closely.  I ran into this Issue and figured I was seeing the same thing.  I have test with bounded and that seems to be working properly.  I will try polling next.  Thanks for the quick and thorough response.

**Comment by laura-rodriguez** [comment]
No worries! I'm glad this was helpful.
