### ISSUE TITLE
Profile attributes not returned with 

### ISSUE THREAD

**Issue by mattmcnabb** [okta/okta-sdk-dotnet#340]
According to the [API reference](https://developer.okta.com/docs/reference/api/apps/#application-group-properties) the application group resource should return the application group profile which I assume should contain details of the profile mappings for the group. However, the [ApplicationGroupAssignment](https://github.com/okta/okta-sdk-dotnet/blob/80f315daf2b53cc9b929f2776248bd6788184cfb/src/Okta.Sdk/Generated/ApplicationGroupAssignment.Generated.cs) object in this SDK does not appear to contain the profile information - it just has the group Id and the priority. Are there any plans to add the profile schema to the Apps API? Thanks!

**Comment by laura-rodriguez** [comment]
Hi @mattmcnabb,

You can still retrieve the profile even though it's not a predefined property. Try the following code:
```
var retrievedAppGroup = await client.Applications.GetApplicationGroupAssignmentAsync(createdApp.Id, createdGroup.Id);
var profile = retrievedAppGroup["profile"];
```
With any `Resource` you can still retrieve information provided by the API, even when it is not defined in the class.

**Comment by mattmcnabb** [comment]
Thanks, I'll look into how to implement this.
