### ISSUE TITLE
Users collection includes duplicates

### ISSUE THREAD

**Issue by andylbrummer** [okta/okta-sdk-dotnet#351]
When iterating over the user collection, duplicate users are returned when a user is updated during the iteration. 

We are working around this issue by grouping on the id and returning the record with the latest LastUpdate date.

**Comment by laura-rodriguez** [comment]
Hi @andylbrummer,

Can you please post a sample of your code? It is going to be useful for us to reproduce the issue.

Thanks!

**Comment by laura-rodriguez** [comment]
Closed due to inactivity.
