### ISSUE TITLE
Where do the generated classes in this repo come from?

### ISSUE THREAD

**Issue by adamdaum** [okta/okta-sdk-dotnet#353]
I use this sdk quite a bit, and was thinking about contributing to it.  However, I'm not familiar with whatever step is generating the generated classes, like all the classes in the Generated folder that end in .Generated.cs.  Could someone direct me to where I can learn more about how those classes are generated?

**Comment by laura-rodriguez** [comment]
Hey @adamdaum,
Thanks for asking!
The existing code is generated automatically based on our openapi spec which is in a private repo, so, unfortunately, we cannot take contributions to the spec. What would you like to add/improve/fix?

**Comment by adamdaum** [comment]
thanks @laura-rodriguez .  I had initially though of adding an enumerable of Application objects to the User Class, because I was surprised not to find one.  However, I realize now, after poking around a bit, that the AppLinks enumerator probably has most of what I need, and perhaps it's intended to serve the purpose of obtaining apps assigned to a user.

But I was sort of expecting a full Application, based off of like IApplication with all its properties.  I was trying to replicate what you'd obtain from the REST endpoint urlbase/api/v1/apps?filter=user.id+eq+{{userid}}.  This is the AppLinks property from the UserClass :
  
public IAsyncEnumerable<IAppLink> AppLinks
            => GetClient().Users.ListAppLinks(Id);

I also think an AppLink isn't as intuitive as an Application.  Either way, though it might not add a ton of value, I thought it would be fun to contribute to a public repo that I use, with a contribution I might use.  But if you have other suggestions, for ways to do that, let me know.

**Comment by laura-rodriguez** [comment]
We appreciate your collaborative spirit ❤️ 
If you want to list applications per user, you can do the following:
```
var apps = await client.Applications.ListApplications(filter: $"user.id eq \"{user.Id}\"").ToList();
```

Does it help?

**Comment by adamdaum** [comment]
I mean .. it gets me what I need yes.
