### ISSUE TITLE
Is `OktaClient` thread safe?

### ISSUE THREAD

**Issue by caleblloyd** [okta/okta-sdk-dotnet#355]
When using `OktaClient` in a DI container, is it safe to create a Singleton that many threads may simultaneously access?

Would you consider adding a section about thread safety to the README or other form of documentation for this library?

**Comment by laura-rodriguez** [comment]
Hi @caleblloyd ,

This library internally uses [System.Net.Http.HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netstandard-1.3) to send requests. According to Microsoft Docs the following methods are thread safe :

* CancelPendingRequests
* DeleteAsync
* GetAsync
* GetByteArrayAsync
* GetStreamAsync
* GetStringAsync
* PostAsync
* PutAsync
* SendAsync

We use `SendAsync` to send requests in our [DefaultRequestExecutor](https://github.com/okta/okta-sdk-dotnet/blob/06d657b4b1bbbe1f9d8b94ead7cf3f882fd4b6d6/src/Okta.Sdk/Internal/DefaultRequestExecutor.cs#L84) which is thread safe.

Does it help?

**Comment by laura-rodriguez** [comment]
Thinking a little bit more about it, I just responded to one of the many aspects that could determine if a library is thread safe. In general, we try to create classes which members can be set only during creation. By doing this we ensure that no code outside the initialization tries to modify any of the properties. For example, you can check out how an `OktaClient` is created and track what happens with each of its members. Particularly, `DefaultRequestExecutor` which is responsible for sending the requests via `System.Net.Http.HttpClient.SendAsync` (thread safe as per MS docs), is initialized during `OktaClient` creation and all of its members are `readonly`. As I said, this is the general design, but if you find any cases which are not thread safe or you have any specific case you want to discuss, please let us know. Thanks for your question!

**Comment by caleblloyd** [comment]
Thanks for your response.  Since `OktaClient` primarily uses `HttpClient`, I did some reading on whether or not `HttpClient` should be used as a Singleton.  Microsoft has an [article detailing issues with the original HttpClient class](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests), which basically states that for .NET Core 2.1 and greater they recommend using `IHttpClientFactory`

Microsoft provides another [detailed article on IHttpClientFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1), and it appears that `OktaClient` is setup to use the `Typed Clients` approach, since [HttpClient](https://github.com/okta/okta-sdk-dotnet/blob/9ccd2d89a0e8d85d0b2123679a94c8b51695cc2d/src/Okta.Sdk/OktaClient.cs#L85) is injectable.

A sample configuration in `Startup.cs` would be:

```csharp
using Microsoft.Extensions.DependencyInjection;
using Okta.Sdk;
using Okta.Sdk.Configuration;

...

public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpClient<IOktaClient, OktaClient>();
    services.AddSingleton(m => new OktaClientConfiguration
    {
        OktaDomain = "domain",
        Token = "token"
    });
}
```

It is important to note that:

> The typed [IHttpClientFactory] client is registered as transient with DI.

I believe that this means that consumers of `IOktaClient` would also need to be transient.  Using a singleton would defeat the whole purpose of `IHttpClientFactory`, since it would re-introduce long-lived `HttpClient` objects under the covers

**Comment by caleblloyd** [comment]
I opened a PR to add this best practice to the `README.md` file

**Comment by jakehockey10** [comment]
I don't see anything mentioning threads in the README.  What happened with this discussion?  If I use the sdk in an asp.net web api, how should I configure the OktaClient injection in terms of scoped, transient, or singleton?

**Comment by caleblloyd** [comment]
@jakehockey10 I tried to open a PR to add DI best-practices to the README but it wasn't accepted.  I am using it successfully in a project though, see https://github.com/okta/okta-sdk-dotnet/pull/356/files

**Comment by jakehockey10** [comment]
@caleblloyd thanks for the quick response.  I'll take a look!
