### ISSUE TITLE
ListUsers() returns active users after suspension unless called couple times. 

### ISSUE THREAD

**Issue by cincom-nuryupin** [okta/okta-sdk-dotnet#367]
Okta SDK v1.4.2
I'm running integration tests in postman. The sequence is:
1.  suspend two users.
2.  unsuspend two users.

When 2 request is executed ListUsers() return users with status "Active" but they should be "Suspended", therefore logic for unsuspension fails. 

HOWEVER, if you call ListUsers().ToList() enough times, it will return correct status, which is "SUSPENDED" for both users.

![image](https://user-images.githubusercontent.com/62618725/77473644-27765f80-6dec-11ea-9b27-e2512b26f817.png)

I suspect there has to be some timing issue. Is there a away to avoid this behavior?

**Comment by laura-rodriguez** [comment]
Hi @cincom-nuryupin ,

Thank you for your question.

This is a well-known issue, you can find more info here: https://developer.okta.com/docs/reference/api/users/#list-users-with-search.

If you already know the `userId`, use `GetUserAsync()` instead. 

For more details about API issues, I suggest reaching out to our support team ( developers@okta.com ).  They can examine the details of your particular use case and suggest solutions.
