### ISSUE TITLE
Implement - Create User with Imported Hashed Password

### ISSUE THREAD

**Issue by ConnorJBishop** [okta/okta-sdk-dotnet#402]
## User story

Ability to [create user using imported hashed password](https://developer.okta.com/docs/reference/api/users/#create-user-with-imported-hashed-password) using the SDK.

## Proposed solution

Either a new options class such as `CreateUserWithImportedHashedPasswordOptions` and a corresponding `IUsersClient.CreateUserAsync` to go with it, or by altering the [IPasswordCredential](https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Generated/IPasswordCredential.Generated.cs) interface to support a [Hashed Password Object](https://developer.okta.com/docs/reference/api/users/#hashed-password-object)

## Alternatives considered

Manually creating the HttpRequest instead of using the SDK

**Comment by bryanapellanes-okta** [comment]
Hi @connor-bishop ,

Thank you for taking the time to submit this.

We will discuss this internally and prioritize accordingly.
