### ISSUE TITLE
[Request] Create User With Password Import Inline Hook

### ISSUE THREAD

**Issue by HumanAftrAll** [okta/okta-sdk-dotnet#408]
## User story

As a developer, I want to be able to create users with [password import inline hook](https://developer.okta.com/docs/reference/password-hook/), so that I can easily develop an user importation solution.

## Proposed solution
Either a new options class such as `CreateActiveUserWithInlineHook` and a corresponding `IUsersClient.CreateUserAsync` to go with it, or by altering the [IPasswordCredential](https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Generated/IPasswordCredential.Generated.cs) interface to support a [Password Import Inline Hook](https://developer.okta.com/docs/reference/api/users/#create-user-with-password-import-inline-hook)

## Alternatives considered
Using a `HttpRequest` directly.

**Comment by HumanAftrAll** [comment]
Just implemented it and submitted a [PR](https://github.com/okta/okta-sdk-dotnet/pull/409).

**Comment by laura-rodriguez** [comment]
Hi @HumanAftrAll ,

Thank you for your contribution ❤️ ! Please, give us some time to review your PR. 

Stay tuned for updates!

**Comment by HumanAftrAll** [comment]
Hello, @laura-rodriguez 

Please reach out with any issues my PR might have. It's my first contribution to an open-source repo. =)

I've sent the CLA over email yesterday. 

Cheers!

**Comment by HumanAftrAll** [comment]
The funny part is that I implemented the inline hook because I needed it and won't be able to use it because my app's dotnet core is v 2.2 and I did not realize it lol
*facepalm*

**Comment by laura-rodriguez** [comment]
Hey @HumanAftrAll , why you cannot use it? This SDK is compatible with .NET Core 2.x.

**Comment by HumanAftrAll** [comment]
@laura-rodriguez because of it's dependencies. It cascades on a dependency version mismatch across my whole solution and I'm out of time to solve all the problems right now... in any case, I'm very happy to have contributed. =)

**Comment by laura-rodriguez** [comment]
Oh I see! well, thanks for your contribution anyways 😄
