### ISSUE TITLE
Unable to access the TrustedOriginsClient from IOktaClient

### ISSUE THREAD

**Issue by bmeredith** [okta/okta-sdk-dotnet#413]
I was looking to use the `TrustedOriginsClient` and see it was added in 3.0, but unfortunately it does not seem currently accessible from `IOktaClient`.

As a workaround, I am able to do everything I need using the appropriate `GetAsync`, `PostAsync<T>`, etc. methods on `IOktaClient`, which works great! It's been especially easy since the `ITrustedOrigin` and `TrustedOrigin` objects already exist for me to use.

## Current behavior
Unable to access the `TrustedOriginsClient` from `IOktaClient`.

## Expected behavior
Make calls to the `TrustedOriginsClient` by using `IOktaClient`.

## Environment

- OS:
- Browser: 
- .Net Framework: .Net Core 3.1
- Other:

**Comment by bryanapellanes-okta** [comment]
@bmeredith ,
Sorry for the delayed response and thank you for bringing this to our attention.  I'll review and apply an appropriate code change to address this.  Stay tuned for more.

**Comment by bmeredith** [comment]
Not a problem!

I was actually in the process of submitting a PR which added the `ITrustedOriginsClient` to `IOktaClient`, but I did see a number of integration tests for each of the other clients and wasn't sure how to proceed at that point.

If you'd like, I can go ahead and PR the changes I've made or let you take care of the appropriate changes necessary.

**Comment by bryanapellanes-okta** [comment]
@bmeredith,
If you've already gotten a head start on the appropriate code change, feel free to submit a PR and we can work together to integrate those changes appropriately.  Thanks for jumping in!

**Comment by bmeredith** [comment]
I've gone ahead and submitted PR #414
