### ISSUE TITLE
AuthorizationServer IPolicy.ListPolicyRules (and GetPolicyRuleAsync, UpdatePolicyRuleAsync) return a 404 for policyId

### ISSUE THREAD

**Issue by gopinathdeepak** [okta/okta-sdk-dotnet#415]
## Current behavior
.Net Core 3.1 application, using the Okta.Sdk package (v3.1). Code gets the AuthorizationServer policy, and then attempts to do a ListRules(), at which time the request fails with a 404 (Policy by provided policyId not found).

IAuthorizationServer server = await oktaClient.AuthorizationServers.GetAuthorizationServerAsync(<id>);
IPolicy policy = await server.GetPolicyAsync(<policyId>);

var rules = policy.ListPolicyRules();

await foreach(var rule in rules)
{
    //iterating through the foreach above makes the request and fails with the 404
}

I noted that the HTTP Request being formed is <oktadomain>/policies/<id>/rules, which returns the 404 for Policy. However, if I was to use the href (from _links in the returned json on Policy), it shows <oktadomain>/authorizationServers/<authId>/policies<policyId>/rules.
This URL does work. I am using this to get around this problem.

## Environment

- OS:
Win 10

- .Net Framework: 
.Net Core 3.1

**Comment by laura-rodriguez** [comment]
Hi @gopinathdeepak ,

Thanks for reporting this issue.

This was added to our backlog to be prioritized by the team.

In the meantime, [you can make the call directly to that endpoint with the `OktaClient`](https://github.com/okta/okta-sdk-dotnet#call-other-api-endpoints), which I believe you are already doing.

**Comment by gopinathdeepak** [comment]
Yes, I am using a direct call to that endpoint to get the functionality I need. Thank you! :)

**Comment by laura-rodriguez** [comment]
Hi @gopinathdeepak ,

This was fixed in 4.0.0. Thanks so much for your feedback.

**Comment by gopinathdeepak** [comment]
Thank you for the update!
