### ISSUE TITLE
Errors in README.md

### ISSUE THREAD

**Issue by es-repo** [okta/okta-sdk-dotnet#420]
Examples in `README.md` file contains several calls of sync methods such as `FirstOrDefault`, `ToList`, for example:

```
// Find the desired user
var user = await client.Users.FirstOrDefault(x => x.Profile.Email == "darth.vader@imperial-senate.gov");

// get the user's groups
var groups = await user.Groups.ToList();
```

These methods are not available and their `async` alternatives like `FirstOrDefaultAsync`, `ToListAsync` should be used instead.

**Comment by laura-rodriguez** [comment]
Thanks for the feedback @es-repo! 

I added this to our backlog to be prioritized by the team.
