### ISSUE TITLE
Suggestion for the readme

### ISSUE THREAD

**Issue by dustinparbe** [okta/okta-sdk-dotnet#442]
This statement is the suggested way of "Find the desired user" in several places in the readme:
`var user = await client.Users.FirstOrDefaultAsync(x => x...`

We found out, the hard way, that this might not be a good idea when the collection of Users is large.

May we suggest that Users.FirstOrDefaultAsync is replaced with another method to "Find the desired user" in the readme?
Or perhaps clearify the side effects (with a warning label) of the method, when amount of Users is large?

Thanks!

**Comment by bryanapellanes-okta** [comment]
@dustinparbe ,
Thanks for the suggestion, I've placed an item on our backlog to address this.  Since this is an open source library, feel free to submit a pull request with your proposed changes for consideration, if you're so inclined.

Thanks for using Okta!
