### ISSUE TITLE
Install fails via NuGet in VS 2015 targeting 4.7

### ISSUE THREAD

**Issue by nickgamb** [okta/okta-sdk-dotnet#446]
## Current behavior

![Picture1](https://user-images.githubusercontent.com/7018639/97348204-13478480-184b-11eb-9234-d8046629b32d.png)
![Picture2](https://user-images.githubusercontent.com/7018639/97348217-1773a200-184b-11eb-9bb1-8fb7edb5518a.png)

When installing Okta.Sdk via NuGet in Visual Studio 2015 targeting .NET 4.7.2, the install fails with the error:

"Could not install package 'Okta.Sdk 3.2.0'. You are trying to install this package into a project that targets .NETFramework, Version=v4.7.2, but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Upgrading Visual Studio to a newer version resolves the issue. 

This was reproduced on multiple machines.

## Expected behavior

This may be behaving as expected if VS 2015 is no longer supported but if that is the case, it should be noted in the read-me. 

## Minimal reproduction of the problem with instructions

To reproduce, install VS 2015 (any build) in Windows, use NuGet to search for Okta.Sdk, and install. 

## Environment
 
- OS: Windows 10
- .Net Framework: 
4.7.2

**Comment by bryanapellanes-okta** [comment]
@nickgamb,
Thanks for bringing this to our attention.  I'll add this to the team backlog for review and prioritization.
