### ISSUE TITLE
Error accessing openid configuration file (OKTA .NET core 3.1) 

### ISSUE THREAD

**Issue by rahina-fernandes** [okta/okta-sdk-dotnet#469]
## Current behavior
I have a .NET Core web app that I'm trying to integrate with OKTA. The app needs to be launched via the Okta dashboard. I have the following configuration/code in the ConfigureServices method of the Startup.cs file: 
![image](https://user-images.githubusercontent.com/77968486/105703789-c485b580-5f33-11eb-9200-dc79ced483a7.png)

Where the domain, clientId and ClientSecret are correctly set up in the app.settings.json file. The  [Authorize] header has been added on the controller since we do not have a separate sign-in page.
.Net Core packages installed for Okta : 
![image](https://user-images.githubusercontent.com/77968486/105705911-da48aa00-5f36-11eb-980b-2b9e8daa651e.png)

I am using an Okta enterprise account.
This is the error I get when I click on the app from my OKTA dashboard. (Org details have been masked)
![image](https://user-images.githubusercontent.com/77968486/105705051-a6b95000-5f35-11eb-94e7-a984a9516ec7.png)

Since this is the first time we are trying to configure a .net core web app in okta using an enterprise account,  we were not sure what we were doing wrong. And all the documentation/blogs we came across used an Okta developer account. 

## Expected behavior
The app should redirect to the Okta sign-in page if not already sign-in when I click on it from the Okta dashboard

## Environment
- OS: Windows 10 Enterprise
- Browser: Chrome
- .Net Framework:  .Net Core 3,1
- Other: Okta enterprise account.

**Comment by bryanapellanes-okta** [comment]
@rahina-fernandes ,
Thanks for reaching out, and I apologize for the inconvenience.  I've seen various forms of this kind of failure in the past, something prevents retrieval of the openid connect configuration resulting in an error similar to what you've shared.  This often relates to the use of proxies; are you aware of any proxies in the network topology of your application environment?  Specifically if docker or similar virtualization technology is in use, proxies may exist in a non-obvious way.

**Comment by laura-rodriguez** [comment]
Hi @rahina-fernandes,

Per the error you're getting (`You do not have permissions to access the feature you are requesting`), it seems you don't have access to the `default` Authorization Server. I suggest you talk to your account manager to enable it.

That being said, you should get access to the Org Authorization Server, and you can use it for Web Apps. To configure it, add another line in your configuration to indicate you want to use the Org AS:

```
 .AddOktaMvc(new OktaMvcOptions
           {
                // Replace these values with your Okta configuration
               OktaDomain = Configuration.GetValue<string>("Okta:OktaDomain"),
               AuthorizationServerId = string.Empty,
               ClientId = Configuration.GetValue<string>("Okta:ClientId"),
               ClientSecret = Configuration.GetValue<string>("Okta:ClientSecret"),
               Scope = new List<string> { "openid", "profile", "email" },
           });
```
I hope it helps.

**Comment by hawk4031** [comment]
@bryanapellanes-okta We don't have any proxies in place. In fact, we are using OpenID Connect in other apps (SPAs specifically) with no problems. 

@laura-rodriguez We are using OpenID Connect with other applications (SPAs) using Implicit Flow and these applications do not have any problems. When entering the AuthorizationServerId as an empty string, we receive a 400 Bad Request.

**Comment by bryanapellanes-okta** [comment]
> @bryanapellanes-okta We don't have any proxies in place. In fact, we are using OpenID Connect in other apps (SPAs specifically) with no problems.

Acknowledged.

> @laura-rodriguez We are using OpenID Connect with other applications (SPAs) using Implicit Flow and these applications do not have any problems. When entering the AuthorizationServerId as an empty string, we receive a 400 Bad Request.

Have you tried using the string **"default"** as the AuthorizationServerId?  If this doesn't work it is possible this feature needs to be enabled for your organization; this is something your account manager can enable.

**Comment by hawk4031** [comment]
We originally had `default` as the AuthorizationServerId and that's when we started receiving those errors she mentioned. I can verify that we have the correct feature.

**Comment by laura-rodriguez** [comment]
Hi @hawk4031,

Can you please share what your configuration looks like for this application? I'd like to see the App config on the Okta side and how you're setting up your Okta domain.

Additionally, can you also provide a Fiddler log? That's gonna help us to try to identify the issue.

Thanks!

**Comment by hawk4031** [comment]
Settings for the application in Okta:

Application type: Web
Allowed grant types: Authorization Code and Implicit (both Allow ID Token and Allow Access Token are checked underneath this)
Login Redirect Uris: http://[our dev server]/[app name]/authorization-code/callback
Login Initiated By: Either App or Okta
Application Visibility: Display application icon to users
Login flow: Redirect to app to initiate login
Initiate Login URI: http://[our dev server]/[app name]

Fiddler produces literally nothing. It shows that it makes an attempt to redirect, but we just get the 401 Unauthorized message pertaining to `oauth2/default/.well-known/openid-configuration`

**Comment by laura-rodriguez** [comment]
Thanks for sharing @hawk4031! 
What I want to see if what the request looks like when you set the `AuthorizationServerId = ""` (Org Authz Server). That should work, it's odd you're getting a bad request with that setting.

If you try to navigate to `https://<yourServer>/.well-known/openid-configuration` in your browser, what do you see?

**Comment by hawk4031** [comment]
It says "You do not have permission to access the feature you are requesting". I'm pretty confident that we have this enabled though as we have other OpenID Connect applications setup and they are all working just fine. Is there a particular feature or set of features I can have the admins on our side verify that we have?

**Comment by laura-rodriguez** [comment]
Apologies for the inconvenience.

Since this seems to be related to your Org configuration, I think it might be a good idea for you to contact our developer support team at developers@okta.com so we can have a deeper conversation, and help resolve your problem quicker.

**Comment by hawk4031** [comment]
Will do @laura-rodriguez. I will get that email sent now. Thank you!
