### ISSUE TITLE
The login attribute changed while updating the email attribute

### ISSUE THREAD

**Issue by avisiboni** [okta/okta-sdk-dotnet#470]
## Current behavior
When I updated the user's primary email address, the login attribute was also changed, so the user can no longer log in.

## Expected behavior
The only attribute that needs to be updated is the email.

## Minimal reproduction of the problem with instructions
* Initial the Okta Client with Domain and Api Token
* Fetch user by id.
* Update email attribute in profile object 
* Call UpdateAsync

## Environment

- OS:  Windows
- Browser: N/A

- .Net Framework: Net Core 3.1

- Other: Okta SDK v4.0.0

**Comment by bryanapellanes-okta** [comment]
@avisiboni 
Thanks for reaching out!  I've placed an item on our backlog to review this more closely; we will comment here when we have additional information to share.  Thanks for using Okta!

**Comment by avisiboni** [comment]
@bryanapellanes-okta 
Thank you for your prompt response.

**Comment by laura-rodriguez** [comment]
Hi @avisiboni ,

Can you please share the piece of code you're using to reproduce this issue?

Thanks!

**Comment by avisiboni** [comment]
The registration
`  services.AddHttpClient<IOktaClient, OktaClient>();
            services.AddSingleton(new OktaClientConfiguration
            {
                OktaDomain = configuration.GetValue<string>("OktaConfiguration:Domain"),
                Token =  configuration.GetValue<string>("OktaConfiguration:ApiToken")
            });
`

The update function 

`
    public async Task UpdateUserAsync(string userId, Dictionary<string, string> profileSlice,
            CancellationToken cancellationToken)
        {
            var userToUpdate = await _oktaClient.Users.GetUserAsync(userId, cancellationToken);
            foreach (var (key, value) in profileSlice)
            {
                userToUpdate.Profile[key] = value;
            }
            await userToUpdate.UpdateAsync(cancellationToken);
        }
`
Which invoked with the following parameters
`
new Dictionary<string,string>(){{"email","the email to update"}}
`

**Comment by laura-rodriguez** [comment]
Thanks for sharing, @avisiboni.

After inquiring internally with the corresponding API team, they mentioned that this behavior is expected if you have Self-service registration enabled because it forces email and login to remain in sync. So if you change your email, the user login will change too.

Do you know if you have this feature enabled in your Org? If you are not sure, please contact our developer support team at developers@okta.com to have a deeper conversation and help resolve your problem quicker.

**Comment by avisiboni** [comment]
@laura-rodriguez 
Thanks for your quick response.
But, I've checked our account and self-service registration is disabled.
Please find the attachment below, I hope I'm in the right place.

![image](https://user-images.githubusercontent.com/11908703/106366980-048bd480-6348-11eb-9b7d-cfbc2f252bc8.png)

**Comment by laura-rodriguez** [comment]
Thanks for sharing @avisiboni! 

I suggest reaching out to our developer support team at developers@okta.com, so they can verify your org configuration and help us resolve your issue quicker. There might be other features that can cause this behavior, so they should be able to take a closer look. 

In the meantime, is there any other test org (maybe a developer org) you can use to try to reproduce the issue?

**Comment by avisiboni** [comment]
@laura-rodriguez,

Yes we tried it on a multiple orgs (test & prod) and still, the same result

**Comment by andriizhegurov-okta** [comment]
@avisiboni,  We were able to reproduce this internally and I can confirm that this is the expected behavior and is controlled by internal configuration of an Org. 
If you don't want login and email fields to be linked in this way please contact support and they will change it.

**Comment by avisiboni** [comment]
Thank you very much, @bryanapellanes-okta I just spoke with the vendor support in my country, who confirmed that I need to provide the current login value for each request if I want to avoid the login attribute being updated with the email.

P.S. This applies to API as well.

I hope this will help others.
