### ISSUE TITLE
IApplicationsClient.ListApplicationUsers has a filter argument, but the API doesn't support it.

### ISSUE THREAD

**Issue by sflanker** [okta/okta-sdk-dotnet#484]
I tried using the filter argument of the `ListApplicationUsers` function but as far as I can tell this is not actually supported by the API.

## Current behavior

Any kind of filter parameter results in a 400 Bad Request response with the errorSummary "Invalid search criteria."

Examples I've tried:
 * `externalId eq "my-id"`
 * `id eq "valid-okta-id"`
 * `status eq "ACTIVE"`
 * `credentials.userName eq "valid-username"`
 * `profile.email eq "valid-email"`

## Expected behavior

If this parameter is supported it should not be present on this method.

## Minimal reproduction of the problem with instructions

Hopefully the description above is simple enough to enable an easy repro.

## Environment

- OS: Mac OS
- Browser: N/A
- .Net Framework: .Net Core 3.1 
- Other: Okta.Sdk 5.0.0

**Comment by andriizhegurov-okta** [comment]
Hi @sflanker, I guess you are talking about `q` parameter for `ListApplicationUsers` function. This parameter is checked against several App Users's properties and should contain a sub-string, you cannot use it with expressions. 
Please take a look at the [List users assigned to application documentation](https://developer.okta.com/docs/reference/api/apps/#list-users-assigned-to-application) for details.

**Comment by sflanker** [comment]
@andriizhegurov-okta No, I'm talking about this: https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Generated/IApplicationsClient.Generated.cs#L271 (the `filter` parameter on the `ListApplicationUsers` method). This is bad interface design since this parameter appears to be unsupported (but maybe it's just a documentation issue?). If there is a way to actually use this parameter I would love to know, and a list of supported fields would be great (as exists for other methods that do support this parameter: https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Generated/IApplicationsClient.Generated.cs#L24)

**Comment by andriizhegurov-okta** [comment]
@sflanker Unfortunately it's not currently possible to use a filter with this function.
`filter` parameter doesn't allow any expressions, it is for internal use only and is not documented. 
More information on possible parameters and usage can be found in our [Apps documentation](https://developer.okta.com/docs/reference/api/apps/#list-users-assigned-to-application).
Sorry for inconvenience.
