### ISSUE TITLE
Dependency loop detected for package 'Okta.Sdk'.

### ISSUE THREAD

**Issue by StuartScott5** [okta/okta-sdk-dotnet#485]
## Current behavior
When installing the SDK using "install-package Okta.Sdk" I'm seeing the error below:

install-package : Dependency loop detected for package 'Okta.Sdk'.
At line:1 char:1
+ install-package Okta.Sdk
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Deadlock detected: (Okta.Sdk:String) [Install-Package], Exception
    + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

## Expected behavior
To install without any errors.

## Environment

- OS: Windows 10
- Browser:  Chrome

- .Net Framework: 
 .Net Core 5.0
- Other:

**Comment by andriizhegurov-okta** [comment]
Hi @StuartScott5, I was not able to reproduce this issue with the instructions unfortunately. 
Could you provide more details about your project and environment?
* What versions of Package Manager and Visual Studio do you have? 
* What type of project do you have (console App, WebApi, ...)?
* Are you trying to install the package into a new project or existing one?

**Comment by StuartScott5** [comment]
Hi @andriizhegurov-okta
Thanks for your reply.

- I'm using Visual Studio Code
- It's a WebApi project.
- I'm trying to install into an existing project.
