### ISSUE TITLE
Okta.SDK breaks when calling OktaClient with Yaml version 9

### ISSUE THREAD

**Issue by sorell-cp** [okta/okta-sdk-dotnet#488]
Hello,

I recently have run into an issue with OktaClient breaking in Okta.SDK.  The issue happens in a dependency Okta is using called FlexibleConfiguration.  Currently this package uses Yaml versions 8 and when upgraded to Yaml 9 or later causes a problem.  It's already a known issue on the FlexibleConfiguration github issues list but the author says he will not be updating it.

Exception:

Method not found: 'System.Collections.Generic.IDictionary`2<YamlDotNet.RepresentationModel.YamlNode,YamlDotNet.RepresentationModel.YamlNode> YamlDotNet.RepresentationModel.YamlMappingNode.get_Children()'.

**Comment by andriizhegurov-okta** [comment]
Hi @sorell-cp , thanks for reporting the issue, I have added an item to our backlog. We'll follow up here.

**Comment by tobindh** [comment]
There is now a PR for FlexibleConfiguration to upgrade to the latest YamlDotNet version:
https://github.com/nbarbettini/FlexibleConfiguration/pull/15

**Comment by laura-rodriguez** [comment]
Hi @tobindh,

Thanks for your patience! The team has been super busy with other .NET projects. 

The team will try to review this as soon as possible. Are you currently blocked by this issue?

**Comment by tobindh** [comment]
Not completely blocked, but in the same situation as @sorell-cp in that any other project dependencies that use YamlDotNet have to stay downgraded in order for the Okta SDK to work because of the reliance on the older version of that package.

**Comment by laura-rodriguez** [comment]
We've updated dependencies and released a new version (5.1.0). This might be probably the last update for FlexibleConfiguration since we're planning to use .NET Configuration Providers in the future.

Thanks, everyone!
