### ISSUE TITLE
IUser.Profile does not expose the field "EmployeeType2"

### ISSUE THREAD

**Issue by Christian-Oleson** [okta/okta-sdk-dotnet#501]
- [X] Check that this is not fixed in the latest SDK version (I have the latest installed) 

## Current behavior
IUser.Profile does not expose the field "EmployeeType2". This is exposed in the API JSON. Likewise, this is not documented as a field here:
https://developer.okta.com/docs/reference/api/users/#user-consent-grant-properties

## Expected behavior
 For ease of use, we should expose this string property to allow it to be set.

## Minimal reproduction of the problem with instructions
1. Instantiate a IUsersClient
2. Find any user (which will be of type IUser)
3. Access the IUser.Profile
4. Find that the IUser.Profile does not have the "employeeType2"

## Environment
N/a, this is an issue with the properties exposed in the SDK

## Notes
If desired, I would gladly open a PR to do this. Likewise, if someone can point me to the direction where the Okta API docs are located at, I would gladly update the docs too in order to add the value as a part of the Okta User Profile.

**Comment by andriizhegurov-okta** [comment]
Hi @Christian-Oleson. Thank you for reporting this. We will investigate the issue and update you here.

**Comment by Christian-Oleson** [comment]
I found that this is a custom field on the user profile, so I am closing this issue.
