### ISSUE TITLE
Multi-Target .NET 5 and .NET 6

### ISSUE THREAD

**Issue by Christian-Oleson** [okta/okta-sdk-dotnet#519]
## User story
As a user, I would like to see us Multi-Targeting .NET 5 and .NET 6:
https://www.nuget.org/packages/Okta.Sdk/

## Proposed solution
 Multi-Target .NET 5 and .NET 6

## Alternatives considered
N/a

## Additional information
N/a

**Comment by monde** [comment]
Thanks for the PR @Christian-Oleson , I'll assign some reviewers.
