### ISSUE TITLE
Support MyAccount API

### ISSUE THREAD

**Issue by burkenyo** [okta/okta-sdk-dotnet#524]
## User story
The Okta platform is adding a new MyAccount API for users to manage their own profiles without needing admin access. Thanks to #508, I can now obtain an access token as the user (for example when logging into my Okta-secured app using OIDC), and use it with this SDK.
As the app developer, I would like to use the SDK to access the MyAccount API using strongly-typed C# code.

## Proposed solution
Add `IMyAccount` interface, along with models and concrete types. Add a `MyAccount` property to `OktaClient`.

## Alternatives considered
If I have admin permissions, I can access profiles and profile schema using the users API via `OktaClient.Users`.

## Additional information
Currently, I can access the MyAccount API from C# using direct REST calls, for example with `System.Net.HttpClient`.

**Comment by laura-rodriguez** [comment]
Thanks for your issue! I'll review the status of the /myAccount API internally, and post updates when I have updates to share.

**Comment by laura-rodriguez** [comment]
Per design, the MyAccount API won't be part of the management SDK.

**Comment by burkenyo** [comment]
Hi @laura-rodriguez thanks for the update. I understand the reasoning behind not putting this functionality into the "management" SDK, which suggests use in an admin-style setting. Is there an alternative Nuget Package or C# repo one can use for the MyAccount API?

**Comment by laura-rodriguez** [comment]
Hi @burkenyo,

We don't provide a Nuget package at the moment. 

Would you mind sharing your use case? What type of application do you have?
