### ISSUE TITLE
Unable to create OktaClient on linux build server after 5.2.1 upgrade

### ISSUE THREAD

**Issue by HomelessFreak** [okta/okta-sdk-dotnet#526]
Okta-sdk-dotnet version: 5.2.1 and 5.3.0
Dotnet version: 6.0
Environment: An azure devops build server running some form of linux (can find out if you need)

Issue:
Similar to #515 (but different enough that I thought I would raise it)
After upgrading to 5.2.1 my code is no longer able to create an instance of OktaClient as an exception is thrown.
This works fine on our windows development machines but not on the build servers. The user might be running with restricted access to the rest of the disk, which looking at the code would cause some variables to be null or empty as it tries to resolve the "HomePath"

Exception message:
> path

Exception stack trace:

> at Okta.Sdk.Abstractions.Configuration.Providers.Yaml.YamlConfigurationExtensions.AddYamlFile(IConfigurationBuilder builder, String path, Boolean optional)
>    at Okta.Sdk.OktaClient.GetConfigurationOrDefault(OktaClientConfiguration apiClientConfiguration)
>    at Okta.Sdk.OktaClient..ctor(OktaClientConfiguration apiClientConfiguration, ILogger logger, ISerializer serializer)

**Comment by monde** [comment]
Thanks for reporting this issue @HomelessFreak . We are tracking this internally [OKTA-442387](https://oktainc.atlassian.net/browse/OKTA-442387)

**Comment by laura-rodriguez** [comment]
Hi @HomelessFreak,

Would you mind sharing your OS version and how you're instantiating the OktaClient? Thank you!

**Comment by HomelessFreak** [comment]
Sounds like its on: Amazon Linux 2 LTS AMI

**Comment by 93ramadan** [comment]
Hello
I’m using .net core 3.1 and facing the same issue when deploying to aws serverless lambda - was this pull request accepted ?
Thanks
