### ISSUE TITLE
Scopes sent 3 times when using AuthorizationMode.PrivateKey

### ISSUE THREAD

**Issue by gao-artur** [okta/okta-sdk-dotnet#529]
Hey, I'm using `Okta.Sdk v5.3.1`.
Here is my config
```
  "Okta": {
    "Client": {
      "OktaDomain": "https://***.com",
      "ClientId": "***",
      "AuthorizationMode": "PrivateKey",
      "Scopes": [
        "okta.apps.manage",
        "okta.groups.manage",
        "okta.logs.read",
        "okta.users.manage"
      ],
      "PrivateKey": {
        ***
      }
    }
  },
```

And that's what I see in okta logs: scopes repeated 3 times
![image](https://user-images.githubusercontent.com/4518483/148386576-10e9b673-11e5-4d30-9c29-e44749982157.png)

**Comment by bryanapellanes-okta** [comment]
@gao-artur 
Thanks for reaching out!  To help us understand the issue better, please provide more information about your project and what steps to take to reproduce the issue you see.  If possible please provide a sample project (a link to a repo is preferred if possible).  We'll be happy to help however we can.  Thanks again!

**Comment by gao-artur** [comment]
Sure, I'll prepare simple repro.
I'm replacing api token with OAuth for Okta using [this tutorial](https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/). The bug is not harmful and not causing any problems, I just saw sdk sends all requested scoped 3 time and it looks to me like a bug.

**Comment by gao-artur** [comment]
@bryanapellanes-okta you can find the reproduce [here](https://github.com/gao-artur/okta-sdk-529/tree/master).
Just run and check Fiddler
![image](https://user-images.githubusercontent.com/4518483/148451985-7e9286dc-2e71-476d-80b8-4e3f790e144d.png)
