### ISSUE TITLE
Dot Net SDK for Okta does not Support Filter Operator

### ISSUE THREAD

**Issue by aslamdeshmukh** [okta/okta-sdk-dotnet#547]
### Describe the bug?

Dot Net SDK for Okta does not Support Filter In latest sdk 5.4.1.
There are two filter available in this sdk 1. Search 2. Filter in old sdk both are available. But in  5.4.1 Filter is not available.
We are developing delta reconciliation from okta which will give us Group List whose Membership updated after last Reconciliation. If we are using search we are not getting expected result because Search is not updating data immediately. So Filter is better option for us. But this sdk does not support Filter. Please provide solution for this.

Additiona Details, If we are trying with API: /api/v1/groups?search=lastMembershipUpdated ge "2022-04-21T09:39:42.000Z" and (type eq "OKTA_GROUP") then we are getting "lastMembershipUpdated": "2022-04-25T17:23:31.000Z", But If we are trying with API: /api/v1/groups?filter=lastMembershipUpdated ge "2022-04-21T09:39:42.000Z" and (type eq "OKTA_GROUP") then we are getting accurate date as "lastMembershipUpdated": "2022-04-25T17:35:58.000Z". Search Operator not giving accurate result.
 

### What is expected to happen?

Filter option Should be there in sdk like below.

![image](https://user-images.githubusercontent.com/105188076/167340472-011efe82-841c-4c50-95d8-db589ebd87df.png)

### What is the actual behavior?

Filter option is not there in sdk.
![image](https://user-images.githubusercontent.com/105188076/167340257-53a5f04a-8e28-41c8-9292-0c6f31336c1f.png)

### Reproduction Steps?

Upgrade your application with latest Dot Net sdk 5.4.1. and try to use Filter operator oktaClient.Groups.ListGroups(filter: filter).ToListAsync().Result

### .NET Version

.Net Core 3.1

### SDK Version

Okta.Sdk 5.4.1

**Comment by laura-rodriguez** [comment]
Hi @aslamdeshmukh,

Thanks for bringing this up to our attention. We need to investigate why this param has been removed and fix the open API spec if applicable.

In the meantime, you can still use the client and create a request with all the params you want. Take a look at the "Call other endpoints" [section](https://github.com/okta/okta-sdk-dotnet#call-other-api-endpoints). I hope this helps.

**Comment by laura-rodriguez** [comment]
Internal Ref :OKTA-498007

**Comment by bryanapellanes-okta** [comment]
This should be resolved by the changes made here: https://github.com/okta/okta-management-openapi-spec/pull/133.

Please reopen if I am mistaken.
