### ISSUE TITLE
Deserializing received events from Event Webhook

### ISSUE THREAD

**Issue by philip-young** [okta/okta-sdk-dotnet#550]
### Describe the bug?

In the [Webhook documentation](https://developer.okta.com/docs/concepts/event-hooks/#requests-sent-by-okta) it says Events are sent of type LogEvent. They are, however they are sent as a collection of LogEvent within a `com.okta.event_hook` event - which I am able to parse out using a simple model I created. However, I was just wondering if there is any built in way to deserialize these LogEvents using the Okta .NET SDK.

When I tried using System.Text.Json and the LogEvent class in the SDK (which seems to have properties that match the json I'm being sent) the object isn't deserializing. I noticed there are no JsonPropertyName attributes in the provided LogEvent class, so I also tried using JsonSerializerOptions to ignore casing (and hopefully convert to PascalCase) but no luck there either:
` var oktaLogEvent = JsonSerializer.Deserialize<LogEvent>(json, new JsonSerializerOptions
  {
      PropertyNameCaseInsensitive = true
  });
`
I have tried using Json.NET a bit as well but no success. I can't get the Json to deserialize into the LogEvent object provided by this SDK, the properties come back null. I just thought I would ask if I'm missing something before I go and create another model for LogEvent so I can parse the json I'm receiving from Okta.

### What is expected to happen?

LogEvent Json from Okta gets deserialized into a C# LogEvent using the Okta SDK.

### What is the actual behavior?

The deserialized LogEvent has properties that are null.

### Reproduction Steps?

1. Receive Event of eventType 'com.okta.event_hook' from Okta Webhook.
2.  Parse out collection of LogEvents within (is there a built in Model for com.okta.event_hook to use in this SDK instead?)
3.  Deserialize LogEvent json into the LogEvent C# Object provided by this SDK.

### .NET Version

3.1

### SDK Version

5.0.0

### OS version

BuildNumber  Caption                        OSArchitecture  Version
19044        Microsoft Windows 10 Business  64-bit          10.0.19044

**Comment by bryanapellanes-okta** [comment]
@philip-young 
Thanks for reaching out!  Please review the integration tests found here: https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk.IntegrationTests/LogsScenarios.cs#L63.  Those tests should provide some examples of retrieving log events that are deserialized into the LogEvent objects provided.  Feel free to follow up if this is not sufficient for your needs.

**Comment by philip-young** [comment]
hi @bryanapellanes-okta Thanks for the quick response! I have taken a look at the class you linked. For my scenario, the json is passed into my Webhook, not pulled via the Okta client (but I do have access to it). Is there a way you recommend to use the parsing of that class with json I already have? I am just looking through the code now.

**Comment by bryanapellanes-okta** [comment]
@philip-young After a little investigation, I've found that the model objects defined in the Sdk are designed to be used specifically with the Okta client.  The LogEvent object was unfortunately not designed with your intended usage in mind.  We hope to address this shortcoming in a future release of the Sdk, however it is unclear when this work will be complete.

**Comment by philip-young** [comment]
@bryanapellanes-okta  Yes, I found that there was that dependency and after reviewing the source code I managed to figure out how to do what I needed to do with a mixture of the DefaultSerializer and the ResourceFactory class (see the sample below). I am instantiating the ResourceFactory with a null for both the OktaClient and the ILogger.. can you think of any negative implications of doing this? It seems to be working fine for what I need.. I just need this parsed into the Okta LogEvent C# class to use later.
```
public OktaModelDeserializer()
{
    _resourceFactory = new ResourceFactory(null, null);
    _serializer = new DefaultSerializer();
}

/// <summary>
/// Deserializes an Okta Json Object into a Okta C# Object from the Okta SDK.
/// </summary>
/// <typeparam name="T">The Okta Object Type</typeparam>
/// <param name="json">The json string to be deserialized</param>
/// <returns>A deserialized Okta C# Object of Type <typeparamref name="T"/></returns>
public T Deserialize<T>(string json)
{
    var data = _serializer.Deserialize(json);
    return _resourceFactory.CreateNew<T>(data);
} 
```

**Comment by bryanapellanes-okta** [comment]
@philip-young Sorry for the delayed response.  I'm glad you were able to come up with a solution; I don't see any issues with what you're doing in this code.  Just keep in mind if issues arise it will likely be in the internals of the ResourceFactory.
