### ISSUE TITLE
Group listing expand support

### ISSUE THREAD

**Issue by gilmatok** [okta/okta-sdk-dotnet#553]
### Describe the feature request?

The groups listing API (`/api/v1/groups`) supports the `expand` query param to return additional metadata about the group ([source](https://developer.okta.com/docs/reference/api/groups/#request-parameters-3)).

I need to be able to query the groups' user count.

The current implementation of `IGroupsClient.ListGroups` returns an `IClientCollection<IGroup>` which does not contain the metadata.

### New or Affected Resource(s)

Groups API

### Provide a documentation link

https://developer.okta.com/docs/reference/api/groups/#list-groups

**Comment by gilmatok** [comment]
OK, so turns out the user count is buried deep down inside the `_embedded` dictionary. Isn't there a nicer way to get it?

**Comment by laura-rodriguez** [comment]
Internal Ref: OKTA-723085
