### ISSUE TITLE
Error - Could not load file or assembly 'Okta.Sdk, Version=5.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

### ISSUE THREAD

**Issue by mohitlwcc** [okta/okta-sdk-dotnet#562]
### Describe the bug?

Hi, 

I am trying to use OKTA SDK with my ASP.NET C# MVC project. When I try to call api to create user it gives be below error:

"Could not load file or assembly 'Okta.Sdk, Version=5.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)"

My project has .snk file so does it has anything to do with this error?

Thank you!

### What is expected to happen?

API should create user.

### What is the actual behavior?

Throwing error

### Reproduction Steps?

NA

### .NET Version

4.5

### SDK Version

5.6.0.0

**Comment by bryanapellanes-okta** [comment]
@mohitlwcc Thanks for reaching out!  Yes, because your project has an .snk file it requires all referenced assemblies to also be strong named.  I believe, for simplicity, the Okta Sdk assemblies are not strong named which is the cause of the issue you are seeing.  If it's an option, I'd suggest for you not to sign your assembly in order to reference the Okta.Sdk; however, if this is not an option, you can create a custom build using the Okta.Sdk source if necessary.

**Comment by mohitlwcc** [comment]
Thanks, Bryan, for getting back to me. I think we are not going to opt out of strongly named assembly so can you guide me on how to create a custom build okta.sdk?

Regards,

***@***.***
Mohit Patel
.Net Developer
[O] 1 (225) 231-0751<tel:1%20(225)%20231-0751>

**Comment by bryanapellanes-okta** [comment]
To create a custom build do the following:

- create a key file using sn.exe:
  - start Command Prompt for VS 2022
  - type the command `sn -k okta-sdk.snk`
- clone the repo locally: `git clone https://github.com/okta/okta-sdk-dotnet.git`
- start Visual Studio 2022 and open the solution file: `./src/Okta.Sdk.sln`
- right click the `Okta.Sdk` project and select "properties"
- in the properties window expand "Build" and select "Strong naming"
- check the box labeled "Sign the output assembly to give it a strong name."
- click the "browse" button and select the key file you created in the first step
- build the project

You will now have a custom Okta.Sdk.dll binary with a strong name found in the "bin" directory.

**Comment by mohitlwcc** [comment]
@bryanapellanes-okta Thank you for the guidance. Just want to make sure one thing that if I do custom build sdk and in future if Okta updated something does it going to break anything on my side? Or If any change on okta side takes place does my custom build okta sdk will break?

**Comment by mohitlwcc** [comment]
Hi @bryanapellanes-okta ,

After referring to custom build sdk dll, I am getting below error when I call:

client.Users.GetUserAsync("abc@gmail.com");

CS7069: Reference to type 'IAsyncEnumerable<>' claims it is defined in 'netstandard', but it could not be found

Any Idea?

**Comment by mohitlwcc** [comment]
Just going with unsigned assembly approach.
