### ISSUE TITLE
How to check for User account existance?

### ISSUE THREAD

**Issue by mohitlwcc** [okta/okta-sdk-dotnet#563]
### Describe the bug?

This not bug but was not sure where to seek for help so just opening ticket here.

I am calling "client.Users.GetUserAsync(UserEmail)" API to get user detail. I would like to know how to check if user found or not. Let me know if we can check if user exist using this API or is there any other API available for that.

Thank you!

### What is expected to happen?

Get user details if present or else say user not found.

### What is the actual behavior?

It is throwing error upon not finding user.

### Reproduction Steps?

Call GetUserAsync() API

### .NET Version

4.8

### SDK Version

latest

**Comment by laura-rodriguez** [comment]
Hi @mohitlwcc,

You can find users by using the `q` param as described here: https://developer.okta.com/docs/reference/api/users/#find-users
The SDK's `ListUsers` method exposes all the query params you see in the docs.

I hope this helps.
