### ISSUE TITLE
[iOS] Invalid address error in safari while opening browser with OKTA redirect URI

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [okta/okta-sdk-dotnet#565]
### Describe the bug?

We are using Okta to login into our xamarin forms mobile application. To authenticate the user, our app uses Xamarin.openId.appauth.ios(0.92.0) and xamarin.openId.appauth.android package and log in the user. Now, the issue is only in iOS with redirect URI in the safari browser.

PFB information about the logout implementation. In the below method, Browser.openAsync method is supposed to open the browser with a URL but it does not.

void NavigateToLogout()
{
var authService = DependencyService.Get();
Device.BeginInvokeOnMainThread(async()=>{
var logoutUrl = authService.GetOktaLogoutUrl(Application.Current.Properties[ApplicationProperties.IdToken].ToString());
await Browser.OpenAsync(logoutUrl, BrowserLaunchMode.SystemPreferred);
});
App.IsLoggedIn = false;
var loginProvider = DependencyService.Get();
loginProvider.DeleteAllCookies();
App.Current.MainPage = new NavigationPage(new LoginPage());
}

### What is expected to happen?

The browser should open the below URL without any address invalid error.

Logout URL :

[https://parkplacetech.oktapreview.com/oauth2/ausdfzm97d0rm0DZc0h7/v1/logout?id_token_hint=eyJraWQiOiI5bU5hZ3pwX3J6akhzOHduY0dYQW9FSVNNMlAzbXBQUGprc2RieDBIbkFzIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIwMHUxNnB2eXB4N2g4UjlCcjBoOCIsInZlciI6MSwiaXNzIjoiaHR0cHM6Ly9wYXJrcGx%E2%80%A6](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fparkplacetech.oktapreview.com%2Foauth2%2Fausdfzm97d0rm0DZc0h7%2Fv1%2Flogout%3Fid_token_hint%3DeyJraWQiOiI5bU5hZ3pwX3J6akhzOHduY0dYQW9FSVNNMlAzbXBQUGprc2RieDBIbkFzIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIwMHUxNnB2eXB4N2g4UjlCcjBoOCIsInZlciI6MSwiaXNzIjoiaHR0cHM6Ly9wYXJrcGx%25E2%2580%25A6&data=05%7C01%7Cgnanapriya.n%40infosys.com%7Ccbe03d58117245c560b508da4a228d29%7C63ce7d592f3e42cda8ccbe764cff5eb6%7C0%7C0%7C637903809532821695%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qzMlCREHxWPNOOvgZWkyzz7Ppzg37XQiSZGpuuePGLc%3D&reserved=0)
![image](https://user-images.githubusercontent.com/44390143/180149072-68a267f1-6208-4853-90f7-9f1dea725494.png)

### What is the actual behavior?

Browser says address invalid only in iOS.

### Reproduction Steps?

1. Just need to open the browser in iOS with okta redirect URI

### .NET Version

Microsoft Visual Studio Enterprise 2019
Version 16.11.16
VisualStudio.16.Release/16.11.16+32602.291
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00434-00051-42725-AA725
Microsoft Visual C++ 2019

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.11.106.23128
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.106.23128
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.106.23128
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.11.106.23128
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   12.0.300
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.10
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62205.05200
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/SQLite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### SDK Version

Xamarin.openId.appauth.ios(0.92.0)
Xamarin.Forms  5.0.0.2401

### OS version

C:\>wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                          OSArchitecture  Version
19042        Microsoft Windows 10 Enterprise  64-bit          10.0.19042

**Comment by laura-rodriguez** [comment]
Hi @GnanaPriyaNamasivayam,

Are you using any specific Okta SDK in your Xamarin app?

**Comment by GnanaPriyaNamasivayam** [comment]
Below are the references I use,
![image](https://user-images.githubusercontent.com/44390143/180303431-b4037723-d444-41ff-91ca-28e8efa4464e.png)

**Comment by laura-rodriguez** [comment]
So, it seems you're not using any Okta SDK. I suggest you reach out to developers@okta.com so they can assist you better.

Thanks!
