### ISSUE TITLE
IOktaClient.GetCollection<T> should return an ICollectionClient<T>

### ISSUE THREAD

**Issue by danverde** [okta/okta-sdk-dotnet#581]
### Describe the feature request?

Both overloads of the `GetCollection<T>` method on the `IOktaClient` interface return a concrete `CollectionClient<T>` rather than an `ICollectionClient<T>`. This makes testing a method that contains a call to `GetCollection<T>` difficult since Moq cannot mock a concrete class. The sdk should return the interface to improve testability of these methods.

### New or Affected Resource(s)

Both overloads of `IOktaAdapter.GetCollection<T>()`

**Comment by bryanapellanes-okta** [comment]
@danverde Thanks for reaching out!  You make a good point, I've entered an internal issue for tracking; we'll need to prioritize this against other work.  If you're so inclined, please feel free to submit a pull request with your suggested changes and we can get the ball rolling sooner than later.

Internal Ref: OKTA-530112

Thanks for using Okta!

**Comment by danverde** [comment]
@bryanapellanes-okta Thanks for the quick response. PR has been created & linked to this issue
