### ISSUE TITLE
Not able to set Idp ID when creating routing rule

### ISSUE THREAD

**Issue by aqib-bhat** [okta/okta-sdk-dotnet#587]
### Describe the bug?

**What the goal was**
- Add a routing rule to the default IdP Discovery Policy which routes users with the given email domains to the Identity Provider we had created in Okta.

**The problem we ran into**
- When creating the object of type `IPolicyRuleActions` using the `IdpPolicyRuleActionProvider` constructor, setting the `Id` property gives the error: "A property without setter or inaccessible setter cannot be assigned to".
- The above mentioned Interface and Class in the Okta dotnet SDK:
  - https://github.com/okta/okta-sdk-dotnet/blob/77977d969494bfdac2b87bc5da71fb4dc4d81245/src/Okta.Sdk/Generated/IIdpPolicyRuleActionProvider.Generated.cs
  - https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Generated/IdpPolicyRuleActionProvider.Generated.cs
- Notice the `Type` property has both a getter and a setter defined.
- From https://developer.okta.com/docs/reference/api/policy/#policy-action-object: "Note: IdP types of OKTA, AgentlessDSSO, and IWA don't require an id."
  - So, if we set `Type = "OKTA"`, the call to  `IPolicy ` > `.CreateRuleAsync(routingRule, cancellationToken);` will work but if we want to set Type = "SAML2", we have to also set the `Id` but that is not being allowed.

**The workaround**
- Use the `IOktaClient` > `.PostAsync<PolicyRule>(request: new HttpRequest { ...` call to create the routing rule in the default IdP Discovery Policy.
  - Update the `IPolicyRule` payload to add the Okta Idp Id you wish to pass.
    - Use the `DefaultSerializer` from the OktaSDK as recommended in https://github.com/okta/okta-sdk-dotnet#json-serialization.
    - Modify the JSON to set the `actions.idp.providers` to be an array with the only element having `"type" : "SAML2"` and `"id"` equal to you Okta Idp Id.
- I also verified that if instead of using the Okta dotnet SDK NuGet, I downloaded and referenced that project locally, I could change `IIdpPolicyRuleActionProvider` and `IdpPolicyRuleActionProvider` to have the setter for the `Id` property, and then everything worked smoothly as well.
  - **Note**: These are generated classes, so, the fix needs to take into account how they are generated.

### What is expected to happen?

- Able to set the `Id` property of `IdpPolicyRuleActionProvider`.
- After getting the `IPolicy `object for the default IdP Discovery Policy, calling its method `.CreateRuleAsync(routingRule, cancellationToken);` is successful and creating the routing rule whose action is to use our IdP (whose ID we supplied).

### What is the actual behavior?

When creating the object of type `IPolicyRuleActions` using the `IdpPolicyRuleActionProvider` constructor, setting the `Id` property gives the error:
> A property without setter or inaccessible setter cannot be assigned to.

### Reproduction Steps?

- Create a routing rule using the Okta dotnet SDK in the default IdP Discovery policy in which the action is to route to your SAML2 IdP for some email domains.
- When creating the object of type `IPolicyRuleActions` using the `IdpPolicyRuleActionProvider` constructor, try to set the `Id` property.
  - From https://developer.okta.com/docs/reference/api/policy/#policy-action-object: "Note: IdP types of OKTA, AgentlessDSSO, and IWA don't require an id.". So, set `Type = "SAML2"`.

### .NET Version

6

### SDK Version

5.6.0

### OS version

Windows 10

**Comment by bryanapellanes-okta** [comment]
@aqib-bhat Thanks for bringing this to our attention!  I've entered an internal issue for tracking; this will need to be prioritized against other work.

Internal Ref: OKTA-533711

**Comment by rishigohil** [comment]
@bryanapellanes-okta Do we have a status on this? Do we have a cleaner way to create Routing rules in 7.0.5?

**Comment by laura-rodriguez** [comment]
Fixed in 7.0.6
