### ISSUE TITLE
Listing roles does not work

### ISSUE THREAD

**Issue by klettier** [okta/okta-sdk-dotnet#607]
### Describe the bug?

`IamRole` object seems to require a `Permissions` property
![image](https://user-images.githubusercontent.com/3425823/205701959-f5423f20-a9d1-4a03-8e0e-34717c38aa97.png)

but this property does not exist in the returned payload from `ListRolesAsync` 

![image](https://user-images.githubusercontent.com/3425823/205702492-642e4969-601d-4e12-914b-3e15e7171255.png)

which is causing an exception

![image](https://user-images.githubusercontent.com/3425823/205702030-1b324df5-8a0a-4caa-9ebc-cc0fda8c931c.png)

### What is expected to happen?

Listing roles properly

### What is the actual behavior?

Throwing exception

### Reproduction Steps?

1.  Create `RoleApi`
2.  Call `ListRolesAsync`

### Additional Information?

none

### .NET Version

net6.0

### SDK Version

6.0.1

### OS version

windows 11

**Comment by laura-rodriguez** [comment]
Hi @klettier,

Thanks for reporting this issue. I'll file an internal issue to be prioritized by the team.

Internal Ref: https://oktainc.atlassian.net/browse/OKTA-555501

**Comment by klettier** [comment]
Any update on this?
Thx in advance 🙏

**Comment by laura-rodriguez** [comment]
Hi @klettier,

Thank you for your patience and for bringing this to our attention. I'll make sure this issue has visibility during our planning.
We'll keep you posted.

**Comment by laura-rodriguez** [comment]
Fixed in 6.0.3
