### ISSUE TITLE
UpdateUserAsync should allow updating the user type

### ISSUE THREAD

**Issue by bmatthews-tandemdiabetes** [okta/okta-sdk-dotnet#615]
### Describe the feature request?

The user type can be updated with a full replacement PUT via the [Okta API](https://developer.okta.com/docs/reference/api/users/#request-parameters-4). This is currently not exposed in the UpdateUserRequest class. This class only allows updating credentials or profile. I would like to be able to use the sdk to update the user type instead of calling the API directly.

### New or Affected Resource(s)

- UserApi.UpdateUserAsync
- UpdateUserRequest

### Provide a documentation link

https://developer.okta.com/docs/reference/api/users/#request-parameters-4

**Comment by laura-rodriguez** [comment]
Hi @bmatthews-tandemdiabetes,

Thanks for reporting this issue. Our team will review it and prioritize it accordingly.

Internal Ref: OKTA-575483

**Comment by laura-rodriguez** [comment]
Hi @bmatthews-tandemdiabetes,

Thanks for your patience. 

Can you please provide a sample of what the request looks like when you update the user type via API?

**Comment by laura-rodriguez** [comment]
Fixed in 6.0.7. See the following [test](https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk.IntegrationTest/UserScenarios.cs#L407).
