### ISSUE TITLE
SDK calls with private key authorization mode start returning empty results after inner access token expired

### ISSUE THREAD

**Issue by certara-iyurchenko** [okta/okta-sdk-dotnet#616]
### Describe the bug?

SDK calls with private key authorization mode start sending empty results once inner access token that is generating by SDK expired.

### What is expected to happen?

After inner access token expired it should be refreshed automatically. According to sources it is supporting but seems that there are some issue with that functionality (maybe with access token assigning inside header to call okta rest api internally).

### What is the actual behavior?

After inner access token expired SDK calls stat returning empty results without any exception.

### Reproduction Steps?

 1. Create API Services okta application.
 2. Generate Private Key for new application.
 3. Grant okta.groups.read scope.
 4. Create new .NET 7.0 project with Okta.Sdk dependency and use following code to get okta groups
 
 ```
var configuration = new Configuration
{
	AuthorizationMode = AuthorizationMode.PrivateKey,
	OktaDomain = <okta domain>,
	ClientId = <okta application client id>,
	PrivateKey = new JsonWebKeyConfiguration(<okta application private key>),
	Scopes = new HashSet<string> {"okta.groups.read"}
});

var groupsApi = new GroupApi(configuration);
var groups1 = await groupApi.ListGroups().ToListAsync(); // groups1 contains valid okta groups
<wait while inner access token expired, for example 2 hours>
var groups2 = await groupApi.ListGroups().ToListAsync(); // groups2 list is empty and there are no errors 
```

### .NET Version

7.0.101

### SDK Version

6.0.1

**Comment by laura-rodriguez** [comment]
Hi @certara-iyurchenko,

Thanks for reporting this issue. I'll file an internal ticket to be reviewed and prioritized by the team.

Internal Ref: OKTA-575474

**Comment by certara-iyurchenko** [comment]
@laura-rodriguez Could you please clarify when it plan to fixed?

**Comment by laura-rodriguez** [comment]
Hi 
@certara-iyurchenko, thanks for your patience. 

I'll make sure to put this on the team's radar for prioritization. We'll keep you posted.
