### ISSUE TITLE
Resend SMS as part of enrollment

### ISSUE THREAD

**Issue by MHFAtperrotti** [okta/okta-sdk-dotnet#633]
### Describe the feature request?

When enrolling the SMS factor, a user may want a new code sent to the same phone.  The Factor API supports resending a code via SMS during enrollment of the factor.  The SDK does not include this feature.

### New or Affected Resource(s)

[UserFactorApi.cs](https://github.com/okta/okta-sdk-dotnet/blob/c23340e9da793532e17cf93bf981c4fd2ed07a42/src/Okta.Sdk/Api/UserFactorApi.cs)

### Provide a documentation link

https://developer.okta.com/docs/reference/api/factors/#resend-sms-as-part-of-enrollment

**Comment by laura-rodriguez** [comment]
Hi @MHFAtperrotti,

Thanks for reporting this issue. I'll file an internal ticket to be reviewed and prioritized by the team.

Internal Ref: OKTA-597742

**Comment by laura-rodriguez** [comment]
Fixed in 6.0.8
