### ISSUE TITLE
Create/Update Account returns NULL when okta tenant hits rate limits 

### ISSUE THREAD

**Issue by jcaldwell-tandemdiabetes** [okta/okta-sdk-dotnet#638]
### Describe the bug?

When okta tenant is under heavy load and rate limit events are raised, CreateUserAsync and PartialUpdateUserAsync on IUserApi returns NULL object.

### What is expected to happen?

If the request is unsuccessful, an exception is expected.  The SDK methods are defined to return an object, unless there is an exception condition preventing the operation from completing successfully. 

### What is the actual behavior?

The SDK methods return null object, when the okta server is under heavy load -- ie, rate limit events reported for /api/v1/users (write and read).  The SDK does not throw an exception. The SDK hides the details of rate limit handling and retries, and it returns a null object if the operation is not successful. 

### Reproduction Steps?

Run a migration or test tool that floods the okta tenant with CreateAccountSync and PartialUpdateUserAsync requests that eventually triggers rate limit events on okta. Some of the requests will eventually begin to return null from these iUser methods. 

### Additional Information?

We can consistently trigger this behavior during a user migration from previous OAuth provider to Okta.  Because of this behavior and rate limiting, the migration tool has been modified to limit throughput that does not trigger rate limit events.  However, this increases the length of time required to migrate production user accounts into Okta. 

### .NET Version

mcr.microsoft.com/dotnet/sdk:6.0 

### SDK Version

6.0.8

### OS version

mcr.microsoft.com/dotnet/aspnet:6.0 runtime

**Comment by laura-rodriguez** [comment]
Hi @jcaldwell-tandemdiabetes,

Thanks for reporting this issue. Could you share your retry/connection timeout configuration? Does the issue happen only with the User API? Also, are you using OAuth private key or API token?

**Comment by laura-rodriguez** [comment]
Thanks for the info @jcaldwell-tandemdiabetes !

As you mentioned well, the [SDK handles rate limit out of the box](https://github.com/okta/okta-sdk-dotnet#built-in-retry), but you can "disable" this feature by setting `MaxRetries = 0` in your Okta configuration. Additionally, if you don't wanna use the default retry Polly policy, you can provide your own. 
What's your Okta configuration look like? Do you have "retry" enabled?

**Comment by jcaldwell-tandemdiabetes** [comment]
Hey thanks for quick replies @laura-rodriguez!  No, we don't make any okta config changes -- just the defaults, I'm fairly certain.  I'll confirm

**Comment by jcaldwell-tandemdiabetes** [comment]
@laura-rodriguez, are you suggesting the SDK returning "null" will not occur if we set MaxRetries = 0?

**Comment by laura-rodriguez** [comment]
@jcaldwell-tandemdiabetes, I'm not suggesting anything yet. I want to understand under what conditions you could face this issue. So, [if your Okta configuration is set with MaxRetries = 0, then the SDK shouldn't retry 429 responses](https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Client/ApiClient.cs#L522). Can you provide us with a network/Fiddler/HAR log to analyze the server response?

**Comment by jcaldwell-tandemdiabetes** [comment]
@laura-rodriguez, I saw the PR.  Thanks.  Also wanted to mention that we don't have a network capture because (1) we've already migrated all users to okta, and (2) the migration tool was modified to throttle responses and remain below the rate limit.  It's less likely (although not impossible) we see this in prod, due to anticipated low usage rates hitting our service, which uses this sdk for user/acount management

**Comment by laura-rodriguez** [comment]
Hi @jcaldwell-tandemdiabetes ,
This is definitely an SDK issue, and it's currently fixed and waiting for peer review. It should be shipped anytime soon.

Thanks for reporting it!

**Comment by jcaldwell-tandemdiabetes** [comment]
Thanks Laura! Much appreciated!

**Comment by laura-rodriguez** [comment]
@jcaldwell-tandemdiabetes fix has been published in v6.0.11
