### ISSUE TITLE
Unable to find the .Net sdk method for fetching access, refresh, id token

### ISSUE THREAD

**Issue by gnvrt** [okta/okta-sdk-dotnet#645]
### Describe the bug?

Hi team,
I'm trying to fetch an Access token, Id token, Refresh token for a given input (Authorization code, Redirect Uri) using .Net SDK method, but unable to find an equivalent method for the same.
We do have the Http method for it in here : https://developer.okta.com/docs/reference/api/oidc/#token 

Can you please help me to find the respective .Net SDKs method.

### What is expected to happen?

Find the .Net sdk method for fetching access, refresh, id token

### What is the actual behavior?

No method found to fetch access, refresh, id token

### Reproduction Steps?

No method found to fetch access, refresh, id token

### .NET Version

6

### SDK Version

Okta.SDK - 6.0.7
Okta.Auth.Sdk - 2.0.5

**Comment by laura-rodriguez** [comment]
Hi @gnvrt,

Per design, the management SDK only includes endpoints under `/api/v1`. If you want to hit the token endpoint, you'll have to do it manually.

Thanks!

**Comment by gnvrt** [comment]
Thank you @laura-rodriguez for your response.

All the available .Net SDK's have not any method for accessing these endpoints
1. Authentication - https://developer.okta.com/docs/reference/api/oidc/#token 
     1.1. Endpoint - /api/v1/authn
     1.2. SDK is available - Okta .NET Authentication SDK
2. Token - https://developer.okta.com/docs/reference/api/oidc/#token
     2.1. Endpoint - ${baseUrl}/v1/token
     2.2. SDK is not available 
3. Revoke - https://developer.okta.com/docs/reference/api/oidc/#revoke
     3.1. Endpoint - ${baseUrl}/v1/revoke
     3.2. SDK is not available
4. Keys - https://developer.okta.com/docs/reference/api/oidc/#keys
     4.1. Endpoint - /api/v1/keys
     4.2. SDK is not available


I'm trying to write a wrapper library to have these functionalities like Authentication, Token fetching, Keys etc .  Can you please help me on the same with the available .Net SDK's.
As per my analysis, I have not found a suitable .Net SDK for points (2,3,4). So, I have decided to call these end points manually.

Please help me with your inputs on the above thought process

**Comment by laura-rodriguez** [comment]
Hi @gnvrt,

For what type of applications is your OIDC wrapper indented? The ASP.NET SDK works with Web API, MVC, and Blazor. We also have a Xamarin SDK. If you plan to use the OIDC wrapper in other applications, you might want to check [IdentityModel.OidcClient](https://github.com/IdentityModel/IdentityModel.OidcClient). It already solves OIDC requirements; you can configure it with any OIDC-compliant IDP.  Let me know if this helps!
