### ISSUE TITLE
Factors Api doesn't return factors setup on users

### ISSUE THREAD

**Issue by pdubb29** [okta/okta-sdk-dotnet#650]
### Describe the bug?

Setting multifactors on a user in the Okta api, and attempting to retrieve them using the latest Okta SDK doesn't return any values.

The raw api response when calling through postman returns the expected values.
`/api/v1/users/:userId/factors`

### What is expected to happen?

I should get a list of factors I've configured for the user (4)

### What is the actual behavior?

0 are returned to me from the sdk api call I make with `IUserFactorApiAsync`

### Reproduction Steps?

1. Create a user in the okta admin
2. Activate the user
3. Login to the user 
4. Setup a multifactor (I setup 4 on my user) on the user account.
5. Use Okta SDK to query the factor Api to list the factors with the okta ID

```
var factors = _factorApi.ListFactors("{{oktaId}}", default(CancellationToken));
var factorList = await factors.ToListAsync();
```

### .NET Version

6.0.408

### SDK Version

6.0.11
& All versions of 6

### OS version

```
BuildNumber  Caption                             OSArchitecture          Version
19044        Microsoft Windows 10 Enterprise      64-bit               10.0.19044
```

**Comment by laura-rodriguez** [comment]
HI @pdubb29,

Thanks for reporting this issue. I'll file an internal ticket so it's reviewed and prioritized by the team.

Internal Ref:  OKTA-622582

**Comment by pdubb29** [comment]
Thanks for getting this in!
