### ISSUE TITLE
Can't enroll user in multifactor with SDK because of missing Profile property

### ISSUE THREAD

**Issue by pdubb29** [okta/okta-sdk-dotnet#651]
### Describe the bug?

There's a missing profile property, and can't provision that information to send to the factors api.

This request example:
https://developer.okta.com/docs/reference/api/factors/#request-example-7

cannot be replicated in the SDK, because there is no profile property on this class
https://github.com/okta/okta-sdk-dotnet/blob/f0317653f77e15e0b12d068888429d9346ab8001/src/Okta.Sdk/Model/UserFactor.cs#L4

### What is expected to happen?

I should be able to enroll a multifactor with security question as shown in the request example

### What is the actual behavior?

The request fails because there's nowhere to provision the profile property

### Reproduction Steps?

Provision your factor api with the necessary client configuration
Okta.Sdk.Client.Configuration clientConfig = new Okta.Sdk.Client.Configuration()
            {
                Token = {{oktaApiToken}},
                OktaDomain = {{oktaApiDomain}}
            };

IUserFactorApi userFactorApi = new UserFactorApi(clientConfig);
userFactorApi.EnrollFactorAsync("", new UserFactor()
            {
                     FactorType = new FactorType("question"),
                     Provider = "OKTA",
                     //no profile object in the class, cannot provide what's in this example (https://developer.okta.com/docs/reference/api/factors/#request-example-7)
            });

### .NET Version

6.0.408

### SDK Version

6.0.11

### OS version

BuildNumber  Caption                             OSArchitecture          Version
19044        Microsoft Windows 10 Enterprise      64-bit               10.0.19044

**Comment by laura-rodriguez** [comment]
Hi @pdubb29,

Thanks for reporting this issue. I'll file an internal ticket for our team to be prioritized.

Internal Ref: OKTA-628588

**Comment by laura-rodriguez** [comment]
Hi @pdubb29,

I confirm this is not an issue (at least in the latest version 7.0.1) and you can set a profile by instantiating the proper UserFactor class. See the following PR which contains a few tests that verify what I'm stating here. I hope this helps!

https://github.com/okta/okta-sdk-dotnet/pull/679
