### ISSUE TITLE
Retrieving SAML Identity Provider metadata.xml Using Okta SDK (.NET)

### ISSUE THREAD

**Issue by rishigohil** [okta/okta-sdk-dotnet#663]
### Describe the feature request?

I came through a scenario where I needed to fetch the SAML Identity Provider metadata.xml using the Okta SDK. `IOktaClient` contains a method for IdentityProvider operations but I could not locate a way to directly retrieve the metadata.xml document itself.

Although the SDK offers the metadata.xml URL, we require the metadata document for further processing. Has anyone encountered a similar situation or found a workaround to fetch the SAML IdentityProvider metadata.xml via Okta SDK?

Thank you!

### New or Affected Resource(s)

[[/v1/idps/](https://developer.okta.com/docs/reference/api/idps/)](https://developer.okta.com/docs/reference/api/idps/#get-identity-provider)

### Provide a documentation link

https://developer.okta.com/docs/reference/api/idps/

**Comment by laura-rodriguez** [comment]
Hi @rishigohil,

Thanks for your question. What version of the SDK are you using? Also, did you find the endpoint/API that does what you want in our API documentation? I basically want to know if something's missing in the SDK or if the Okta API doesn't fully support your use case.

**Comment by rishigohil** [comment]
Hello @laura-rodriguez ,

We currently use `GetIdentityProviderAsync` to Get the Idp details using `Okta.Sdk - 5.6.0`. Calling [Get Identity Provider](https://developer.okta.com/docs/reference/api/idps/#get-identity-provider) API providers us the `_links` object and the Idp Metadata would contain the `href` for SAML Identity Provider `metadata.xml`. Do we have the ability to pull metadata documents using SDK or a standalone API that I can call using [GetCollection](https://developer.okta.com/okta-sdk-dotnet/latest/api/Okta.Sdk.OktaClient.html#Okta_Sdk_OktaClient_GetCollection__1_Okta_Sdk_HttpRequest_)?

![image](https://github.com/okta/okta-sdk-dotnet/assets/5967748/091521b2-fbd7-4162-9193-8b902048963c)


Thank you.

**Comment by laura-rodriguez** [comment]
Maybe you can try the following:

1) [Get metadata link from _links](https://github.com/okta/okta-sdk-dotnet/tree/legacy-5.x-series#get-data-from-_links)  
```
var metadataUrl = myIdp.GetProperty<Resource>("_links")?
                .GetProperty<Resource>("metadata")?
                .GetProperty<string>("href");
```
2) [Call the API directly](https://github.com/okta/okta-sdk-dotnet/tree/legacy-5.x-series#get-data-from-_links)
I don't recall if this version of the SDK supports XML files, but if it doesn't, then you'll have to [make the call manually](https://stackoverflow.com/questions/19942486/how-to-use-httpclient-to-read-an-xml-response). 

I suggest you try first via Postman, and once you are sure about what the request looks like, port it to your C# code.

I hope this helps.

**Comment by rishigohil** [comment]
Yes, we are currently calling it manually but we were looking for a way to perform the same using the SDK to leverage all its internal features like auto-renewing the token. Do you have a method exposed for this operation in the latest version of the SDK or is that something in the works? 

Thank you.

**Comment by laura-rodriguez** [comment]
I see. Unfortunately, if the API doesn't expose a better way to get the metadata, that's currently your only option, regardless of the SDK version.

I suggest filing a feature request to allow the SDK to make requests to links leveraging all its internal features, like auto-renewing the token. We'll monitor it and gauge people's interest.
