### ISSUE TITLE
Upgrade Okta.Sdk 6.0 to 7.0: MFA not able to get transactionId

### ISSUE THREAD

**Issue by 3sRykaert** [okta/okta-sdk-dotnet#665]
### Describe the bug?

After I upgraded the Okta.Sdk from 6.0 to 7.0, I cannot fetch the transactionId anymore.
I have an app where I need to verify against Okta, where a user sent his username & password.
Then the Okta app on the user his phone gets a msg, where the user has to verify it is him.
With Okta.Sdk 6.0 I get a VerifyUserFactorResponse (at userFactorApi.VerifyFactorAsync) with some "links" from which i can retrieve the transactionId in the "Link" property.
It seems like the [https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Model/VerifyUserFactorResponse.cs](https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Model/VerifyUserFactorResponse.cs) doesn't corresponds with the answer from the api anymore (as mentioned in [https://developer.okta.com/docs/reference/api/factors/#response-example-25](https://developer.okta.com/docs/reference/api/factors/#response-example-25)

I have the following code
```c#
private async Task DoLogonAsync(string userName, string password, CancellationToken cancellationToken)
    {
        var authClient = new AuthenticationClient(new OktaClientConfiguration
        {
            OktaDomain = "someOktaDomain"
        });

        var authResponse = await authClient.AuthenticateAsync(new AuthenticateOptions
        {
            Username = userName,
            Password = password
        }, cancellationToken);


        if (authResponse.AuthenticationStatus == AuthenticationStatus.MfaRequired)
        {
            var oktaConfig = new Configuration
            {
                OktaDomain = "someOktaDomain",
                Token = "someOktaApiToken"
            };

            var userApi = new UserApi(oktaConfig);
            var user = await userApi.GetUserAsync(userName, cancellationToken);

            var userFactorApi = new UserFactorApi(oktaConfig);
            var factors = await userFactorApi.ListFactorsWithHttpInfoAsync(user.Id, cancellationToken);

            var factor = factors.Data.FirstOrDefault(x => x.FactorType == Okta.Sdk.Model.FactorType.Push);
            if (factor != null)
            {
                var result = await userFactorApi.VerifyFactorAsync(user.Id, factor.Id, null, cancellationToken: cancellationToken);

            }
        }
    }
```

### What is expected to happen?

Get a VerifyUserFactorResponse from which I can fetch the transactionId

### What is the actual behavior?

The links in the VerifyUserFactorResponse are null.

### Reproduction Steps?

See code above

### .NET Version

dotnet 7.0

### SDK Version

6.0 & 7.0

**Comment by laura-rodriguez** [comment]
Hi @3sRykaert,

Would you mind sharing how you obtained the transaction ID before and what the response looked like before vs. now? I want to understand is this is either an issue in the SDK that is not parsing the response properly or a breaking change in the API.

**Comment by 3sRykaert** [comment]
As far as I see it, it is an issue in SDK, since the response stays the same: the VerifyUserFactorResponse doesn't corresponds with the response from the api.
Also in Okta SDK 5.x you could do the following to get the transaction Id:
```c#                   
var result = await client.UserFactors.VerifyFactorAsync(user.Id, factor.Id, null, cancellationToken);
var transactionId = result.GetTransactionId();
```
In Okta SDK 6.x result.GetTransactionId() isn't available anymore, so I had to it "manually" the following way:
```c#                   
    public string GetTransactionId(VerifyUserFactorResponse verifyUserFactorResponse)
    {
        //method in the package was removed, so this code is based on:
        //https://github.com/okta/okta-sdk-dotnet/commit/41ac3fde0b83b8eb0a708990cf843b119fa18dc5#diff-4f19756e98ed99ad240b60549d74f67ad9d579d948b2076bae66001c75a1c8c9
        //see for documentation:
        //https://developer.okta.com/docs/reference/api/factors/#request-example-37
        //private const string TransactionsSegmentName = "transactions";

        string transactionId = null;

        if (verifyUserFactorResponse?.Links != null
            && verifyUserFactorResponse.Links.TryGetValue("poll", out var o)
            && o is Newtonsoft.Json.Linq.JObject j
            && j.TryGetValue("href", StringComparison.InvariantCultureIgnoreCase, out var jToken)
            && jToken is Newtonsoft.Json.Linq.JValue jValue
            && jValue.Value != null
            && Uri.TryCreate(jValue.Value.ToString(), UriKind.Absolute, out var uri))
        {
            var indexOfTransactions = Array.FindIndex(uri.Segments, x => string.Equals(x.Replace("/", ""), "transactions", StringComparison.InvariantCultureIgnoreCase));
            if (uri.Segments.Length >= indexOfTransactions)
                transactionId = uri.Segments[indexOfTransactions + 1].Replace("/", "");
        }
        return transactionId;
    }
```

**Comment by laura-rodriguez** [comment]
@3sRykaert thanks for sharing more details. We'll have to review the open API spec with the corresponding API team and port the solution to the SDK.
