### ISSUE TITLE
Nuget package missing License information

### ISSUE THREAD

**Issue by metoule** [okta/okta-sdk-dotnet#667]
### Describe the bug?

The Nuget packages published at https://www.nuget.org/packages/Okta.Sdk/ are missing the License information. Based on this Github repo, I assume the license is Apache-2.0, but can you please add the information to the packages? 

The instruction can be found here: https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg, but it should be as easy as adding `<license type="expression">Apache-2.0</license>` to your `.nuspec` file.

### What is expected to happen?

The License information should be included in the published packages. 

### What is the actual behavior?

No license is found.

### Reproduction Steps?

N/A

### .NET Version

N/A

### SDK Version

All versions are affected

**Comment by laura-rodriguez** [comment]
Hi @metoule,

Thanks for your issue. I'll file an internal ticket to be prioritized by the team.

Internal Ref: OKTA-653507
