### ISSUE TITLE
Unable to use the profile property in UserFactor

### ISSUE THREAD

**Issue by sero323** [okta/okta-sdk-dotnet#684]
### Describe the bug?

I am able to use `UserFactorApi.ListFactors(uid)` to get a list user's factors. I do not like how the sdk organizes the data, so i created my own model, to then assign to it what i need. The issue is that when i access the profile property i always get null. I investigated a little more by inspecting the UserFactor model, and i saw that there are two "Profile" properties. One is of type System.Object (which is the one that is returned as null) and the other could be basically any of the UserFactorProfile types (CallUserFactorProfile, SmsUserFactorProfile, EmailUserFactorProfile, etc.).
I was able to use reflections to access the property that has the actual Profile, but i would expect it to return the profile when i access UserFactor.Profile.

See screenshot from debugger below....
<img width="558" alt="Screenshot 2023-12-06 at 4 17 06 PM" src="https://github.com/okta/okta-sdk-dotnet/assets/22666128/1f334049-739c-4a4b-aee9-d18a60b4762f">

### What is expected to happen?

Return the profile when i access UserFactor.Profile.

### What is the actual behavior?

see above bug description....

### Reproduction Steps?

This contains an array of UserFactor objects which would return a null for the Profile property.
`var enrolledFactorsFromOkta = await _okta.userFactorApi.ListFactors(uid).ToArrayAsync();`

### .NET Version

.NET SDK: 6.0.203
.NET Runtime: 6.0.5

### SDK Version

7.0.1

### OS version

MacOS 14.0

**Comment by laura-rodriguez** [comment]
Hi @sero323,

Thanks for reporting this issue. I'll file an internal ticket to be reviewed by the team.

We also value your feedback on models, would you mind elaborating a bit more on why you don't like how models are organized?  For context, models are autogenerated using the Okta management OpenAPI spec.

**Comment by sero323** [comment]
HI @laura-rodriguez, I take that back, i believe i was trying something on an older sdk version (5) and what i observed is no longer the case in 7.0.1. If you're curious though, i was seeing the case where say for factorType (as an example), i would have to access the type by doing factorType.Value. And it just felt unnecessary to do .Value to retrieve the value. But again, i dont see that to be the case any longer in sdk 7.0.1
