### ISSUE TITLE
API Gap - IdP Discovery Policy Rule does not exist

### ISSUE THREAD

**Issue by rcollette** [okta/okta-sdk-dotnet#687]
### Describe the bug?

An IDP discovery policy type does not appear to be defined in the SDK, and seemingly this makes it not possible to create these types along with their associated rules and actions.

This was possible in older versions of the SDK.

```c#
  /// <summary>
  /// Template: ModelGeneric
  /// PolicyRule
  /// </summary>
  [DataContract(Name = "PolicyRule")]
  [JsonConverter(typeof (JsonSubtypes), new object[] {"Type"})]
  [JsonSubtypes.KnownSubType(typeof (AccessPolicyRule), "ACCESS_POLICY")]
  [JsonSubtypes.KnownSubType(typeof (AccessPolicyRule), "AccessPolicyRule")]
  [JsonSubtypes.KnownSubType(typeof (AuthorizationServerPolicyRule), "AuthorizationServerPolicyRule")]
  [JsonSubtypes.KnownSubType(typeof (OktaSignOnPolicyRule), "OktaSignOnPolicyRule")]
  [JsonSubtypes.KnownSubType(typeof (PasswordPolicyRule), "PASSWORD")]
  [JsonSubtypes.KnownSubType(typeof (ProfileEnrollmentPolicyRule), "PROFILE_ENROLLMENT")]
  [JsonSubtypes.KnownSubType(typeof (PasswordPolicyRule), "PasswordPolicyRule")]
  [JsonSubtypes.KnownSubType(typeof (ProfileEnrollmentPolicyRule), "ProfileEnrollmentPolicyRule")]
  [JsonSubtypes.KnownSubType(typeof (AuthorizationServerPolicyRule), "RESOURCE_ACCESS")]
  [JsonSubtypes.KnownSubType(typeof (OktaSignOnPolicyRule), "SIGN_ON")]
  public class PolicyRule : IEquatable<PolicyRule>
```

There also appears to be an IdPPolicyRuleAction type but is completely unused within the SDK

### What is expected to happen?

It should be possible to create and IdP Discovery Policy Rule and actions using the SDK, since it is possible to do it with REST API calls.

### What is the actual behavior?

None.

### Reproduction Steps?

N/A

### .NET Version

8.0.100

### SDK Version

7.0.2

**Comment by laura-rodriguez** [comment]
Thanks for reporting this issue! An internal ticket has been created to be reviewed and prioritized by the team.

Internal Ref: OKTA-681917

**Comment by rishigohil** [comment]
@laura-rodriguez Do we have a timeline on when this functionality will be added in SDK?

**Comment by laura-rodriguez** [comment]
Hi @rishigohil,

Thank you so much for your patience. Unfortunately, I cannot share timelines, but I'll make sure to put this ticket back on the team's radar. 

To provide additional context, the fix requires changes in the schema and the OpenAPI specification, so we depend on API teams to fix the spec.

**Comment by rishigohil** [comment]
Understood. Thank you for the details. Basically, we're trying to create Idp-Discovery policy rule with user identifiers and idp providers. 

`{
    "status": "ACTIVE",
    "name": "{{RoutingRuleName}}",
    "priority": 1,
    "system": false,
    "conditions": {
        "network": {
            "connection": "ANYWHERE"
        },
        "platform": {
            "include": [
                {
                    "type": "ANY",
                    "os": {
                        "type": "ANY"
                    }
                }
            ],
            "exclude": []
        },
        "userIdentifier": {
            "patterns": [
                {
                    "matchType": "SUFFIX",
                    "value": "domain1.com"
                },
                {
                    "matchType": "SUFFIX",
                    "value": "domain2.net"
                }
            ],
            "type": "IDENTIFIER"
        },
        "app": {
            "include": [],
            "exclude": []
        }
    },
    "actions": {
        "idp": {
            "providers": [
                {
                    "id": "{{oktaIdpId}}",
                    "name": "{{idpName}}",
                    "type": "SAML2"
                }
            ],
            "idpSelectionType": "SPECIFIC"
        }
    },
    "type": "IDP_DISCOVERY"
}`

In Okta SDK 5.x, we used to create `PolicyRule` object with `Conditions` and `Actions` properties set with domains and idp provider information respectively. 

We then used to oktaClient.PostAsync<PolicyRule> to `/api/v1/policies/{{policyid}}/rules" and that created IDP discovery rule successfully. 

With new SDK, we do not see `Conditions` and `Actions` properties.

**Comment by rcollette** [comment]
When calling 

```
 AccessPolicyRule policyRule = await oktaPolicyClient.GetPolicyRuleByRuleIdAsync(ruleId);
```

The Actions property is empty 
![image](https://github.com/okta/okta-sdk-dotnet/assets/136476/dba9782f-995a-4386-859f-87e8c95b0cc5)

When there are in fact defined actions
![image](https://github.com/okta/okta-sdk-dotnet/assets/136476/27e6d12a-cd80-4604-8eec-1c7b1adcdbc1)

I suspect it is related to this issue.

**Comment by BaileyFirman** [comment]
I am upgrading from 6.0.11 -> 7.0.5 and am not able to construct the IDP actions, I believe this is related to the root issue.
The latest diff shows the property among others being removed and a wider search does not show IdpPolicyRuleAction as a property on any other class.

EX:
```
var policyRule = new OktaSignOnPolicyRule
{
    Type = PolicyRuleType.IDPDISCOVERY,
    Name = ".....",
    Actions = new OktaSignOnPolicyRuleActions
    {
        Idp = new IdpPolicyRuleAction // Definition for IDP no longer exists
        {
            Providers = new List<IdpPolicyRuleActionProvider>
            {
                new IdpPolicyRuleActionProvider
                {
                    Type = "....."
                },
            },
        },
    },
```

**Comment by laura-rodriguez** [comment]
Hey Everyone, 
Thank you so much for your patience. 

We do have a PR ready for review that should solve this issue. Please feel free to chime in and give us your feedback.

#707
