### ISSUE TITLE
UserSchemaAttributes minLength and maxLength are non-nullable and cause array schema attribute creation to fail.

### ISSUE THREAD

**Issue by rcollette** [okta/okta-sdk-dotnet#702]
### Describe the bug?

SMH.  At what point does Okta realize that we are paying customers, and it is just embarrassing how many bugs there are that are not being fixed in this SDK?

In the UserSchemaAttribute class, the properties minLength and maxLength are non-nullable.  When creating an array type attribute, minLength and maxLength properties are being sent with a value of 0.  This causes `ISchemaApiAsync.UpdateApplicationUserProfileAsync()` to fail with the error message `Api validation failed: The type: array is not a string type and supported with minLength and maxLength.`

### What is expected to happen?

minLength and maxLength properties should not be sent (null)

### What is the actual behavior?

minLength and maxLength properties are sent with a zero value.

### Reproduction Steps?

Get an existing UserSchema and add an array attribute to it

```
Dictionary<string, UserSchemaAttribute> customAttributes = userSchema.Definitions.Custom.Properties ??
                                                                   throw new InvalidOperationException(
                                                                       "Custom attributes are null.");
 var userSchemaAttribute = new UserSchemaAttribute
        {
            Type = UserSchemaAttributeType.Array,
            Title = "someName",
            Required = false,
            Scope = UserSchemaAttributeScope.NONE,
            ExternalName = "someExternalName",
            Items = new UserSchemaAttributeItems { Type = "string" }
        };
customAttributes.Add(attributeName, userSchemaAttribute);
schemaApiAsync.UpdateApplicationUserProfileAsync(idpId,userSchema)
```

### .NET Version

8.0.200

### SDK Version

8.0.200

### OS version

Darwin MacBook-Pro-3.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

**Comment by laura-rodriguez** [comment]
Thank you so much for taking the time to report this issue and sharing your concerns with us. We take your feedback seriously. We have been surfacing these concerns to the team and will be working on improvements to the OpenAPI specification and SDKs. 
I'll make sure to give visibility to this, and other issues so we can prioritize them as soon as possible.

**Comment by bryanapellanes-okta** [comment]
@rcollette I appreciate your patience while we address this issue.  I've submitted a pull request with the changes necessary to address this bug.  Please feel free to review and comment while we also review within the team: https://github.com/okta/okta-sdk-dotnet/pull/713

**Comment by bryanapellanes-okta** [comment]
This is corrected in v8
