### ISSUE TITLE
PolicyRule does not allow a null Priority to be specified.

### ISSUE THREAD

**Issue by rcollette** [okta/okta-sdk-dotnet#719]
### Describe the bug?

When creating an IdpDiscoveryPolicy, the API allows a null value to be specified for the rule, in which case the rule will be added just prior to the default rule.   The SDK declares the PolicyRule.Priority property as type int rather than as type int? which prevents passing a null value when creating an IdpDiscoveryPolicyRule.

The value is specifically documented as not being required:
https://developer.okta.com/docs/reference/api/policy/#policy-object

### What is expected to happen?

I should be able to not specify a value for Priority and have it send a null value.

### What is the actual behavior?

A priority of zero is sent when I don't specify a Priority, and an error results since 1 is the minimum allowed value.

### Reproduction Steps?

This is pretty straight forward to identify.

### .NET Version

8.0.300

### SDK Version

7.0.6

### OS version

Darwin MacBook-Pro-3.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

**Comment by bryanapellanes-okta** [comment]
@rcollette Thanks for reporting this.  I've added an internal issue for tracking.

OKTA-735157
