### ISSUE TITLE
Okta Configuration: UseProxy was not taken for api configurations

### ISSUE THREAD

**Issue by SoledadIce** [okta/okta-sdk-dotnet#724]
Hi @bryanapellanes-okta,

I just ran into the same issue today. The issue persists in 8.0.1 after the PR #722
And I daggered into the code for a while, the root cause is that the newly introduced `UseProxy` config hasn't been added to the extension method `MergeConfigurations`. So, the config is not properly set for most of the Apis.

Could you please kindly make a hotfix? Thanks!

_Originally posted by @SoledadIce in https://github.com/okta/okta-sdk-dotnet/issues/691#issuecomment-2203799808_

**Comment by SoledadIce** [comment]
I just create this as a new issue in case the comment I left was not noticed. 

original issue: #691 
original PR: #722

**Comment by bryanapellanes-okta** [comment]
@SoledadIce Thanks for reporting this issue! I've entered an internal issue for tracking and prioritization: OKTA-745408

**Comment by bryanapellanes-okta** [comment]
@SoledadIce Please review PR #741; can you confirm that the change there corrects the problem?
