### ISSUE TITLE
The CreateUserAsync creates federated user in pending activation state

### ISSUE THREAD

**Issue by webteckie** [okta/okta-sdk-dotnet#748]
### Describe the bug?

Upgraded to v9.0.0 and the following code fails to create a federated user:
```
        var newUser = await _userApi.CreateUserAsync(new CreateUserRequest
        {
            Profile = new UserProfile
            {
                FirstName = firstName,
                LastName = lastName,
                Email = email,
                Login = email,
                AdditionalProperties = additionalProperties
            },
            Credentials = new UserCredentials
            {
                Provider = new AuthenticationProvider
                {
                    Type = AuthenticationProviderType.FEDERATION,
                }
            }
        }, true, true, null, cancellationToken);
```

The result is a user that has OKTA as the type and the user is created in the `Pending user action` state :

![image](https://github.com/user-attachments/assets/ae7a9154-c38e-47a2-8f12-14920d76fc68)

### What is expected to happen?

Create the user as a federation user and in the active state.

### What is the actual behavior?

The result is a user that has OKTA as the provider type and the user is created in the `Pending user action` state.

### Reproduction Steps?

Use the provided code to add the user.

### .NET Version

8.0.403

### SDK Version

9.0.0

**Comment by bryanapellanes-okta** [comment]
@webteckie Thanks for bringing this to our attention.  At first glance this appears to be an issue with the API, I've entered an internal issue for prioritization and tracking: OKTA-821863.  We will work with the appropriate team to address the issue.

**Comment by piers-smartwyre** [comment]
We are also experiencing this issue on the latest version (9.0.0). With authentication type AuthenticationProviderType.SOCIAL. Is there an update on the fix?

**Comment by bryanapellanes-okta** [comment]
@webteckie So far in our internal investigation we have not yet been able to reproduce the behavior described here.  Do you observe the same behavior using version 8.1.5 of the Sdk?

**Comment by webteckie** [comment]
@bryanapellanes-okta we had to downgrade to 8.1.5 precisely because of that issue with 9.0.0 Testing this again in 9.0.0 is going to take me some time, I'll try to get to it later today or if not some time this week. But if appears that @piers-smartwyre also ran into a similar issue?

**Comment by webteckie** [comment]
@bryanapellanes-okta here you go:

![image](https://github.com/user-attachments/assets/434c2c04-ec99-4ab1-a811-69cfefafd171)

Again, the code being used to add the user is in the OP.

**Comment by bryanapellanes-okta** [comment]
> @bryanapellanes-okta still showing as a problem for me:
> 
> Again, the code being used to add the user is in the OP.

@webteckie Pardon my ignorance, what is `OP`?

**Comment by webteckie** [comment]
> > @bryanapellanes-okta still showing as a problem for me:
> > 
> > Again, the code being used to add the user is in the OP.
> 
> @webteckie Pardon my ignorance, what is `OP`?

@bryanapellanes-okta sorry, Original Post of this issue.🙂
