### ISSUE TITLE
The `AppLink` object doesn't match the API shape since v9.0.0

### ISSUE THREAD

**Issue by gao-artur** [okta/okta-sdk-dotnet#750]
### Describe the bug?

Before the v9 I used to call `ListAppLinks` to find all the applications the user is assigned to
```c#
var userAppIds = _oktaUserApi.ListAppLinks("user id").Select(appLink => appLink.AppInstanceId);
```

Starting v9, the [AppLink](https://github.com/okta/okta-sdk-dotnet/blob/v9.0.0/docs/AppLink.md) doesn't have the `AppInstanceId` property anymore.
According to [API docs](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/UserResources/#tag/UserResources/operation/listAppLinks) it should be there.

Is the model wrong, or does this functionally exist in another API now? How can I list apps with v9?

### What is expected to happen?

I should be able to list all the application IDs to which the user is assigned.

### What is the actual behavior?

The `AppLinks` is missing `AppInstanceId` property.

### Reproduction Steps?

```c#
var userAppIds = _oktaUserApi.ListAppLinks("user id").Select(appLink => appLink.AppInstanceId);
```

### .NET Version

8.0.400

### SDK Version

9.0.0

### OS version

| BuildNumber | Caption                                          | OSArchitecture | Version       | 
|----------------|--------------------------------------|------------------|--------------|
| 19045             | Microsoft Windows 10 Enterprise | 64-bit                | 10.0.19045 |

**Comment by bryanapellanes-okta** [comment]
@gao-artur Thank you for bringing this to our attention.  I've entered an internal issue for tracking and prioritization: OKTA-821867.  

We will consult with the internal team that owns this area of the API and request further guidance be provided here.  A patch will be provided if this is determined to be an oversight.

**Comment by FD5370** [comment]
I have also encountered this issue when updating the nuget of the sdk. When the fix qill be published ?
