### ISSUE TITLE
User integration test: Get Reset Password URL

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-dotnet#84]
1. Create a user with credentials, activated by default → POST /api/v1/users?activate=true

```js
const newUser = {
    profile: {
        firstName: 'John',
        lastName: 'Get-Reset-Password-URL',
        email: 'john-get-reset-password-url@example.com',
        login: 'john-get-reset-password-url@example.com'
    },
    credentials: {
        password: { value: 'Abcd1234' }
    }
};
```

2. Reset the user password → POST /api/v1/users/{{userId}}/lifecycle/reset_password?sendEmail=false
3. Verify that the response returned contains the reset password link
4. Deactivate & delete the user → POST /api/v1/users/{{userId}}/lifecycle/deactivate + DELETE /api/v1/users/{{userId}}

**Comment by leebrandt** [comment]
a-merged...
