### ISSUE TITLE
Group integration test: Group User Operations

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-dotnet#93]
- [ ]  Create a user with credentials → POST /api/v1/users?activate=false

```js
const newUser = {
    profile: {
        firstName: 'John',
        lastName: 'With-Group',
        email: 'john-with-group@example.com',
        login: 'john-with-group@example.com'
    },
    credentials: {
        password: { value: 'Abcd1234' }
    }
};
```

- [x]  Create a new group → POST /api/v1/groups

```js
const newGroup = {
    profile: {
        name: 'Group-Member API Test Group'
    }
};
```

- [x] Add user to the group and validate user present in group → POST /api/v1/groups/{{groupId}}/users/{{userId}} + GET /api/v1/groups/{{groupId}}/users

- [x]  Remove user from group and validate user removed → DELETE  /api/v1/groups/{{groupId}}/users/{{userId}} + GET /api/v1/groups/{{groupId}}/users

- [x]  Delete the group and user → POST /api/v1/users/{{userId}}/lifecycle/deactivate + DELETE /api/v1/users/{{userId}} +  DELETE /api/v1/groups/{{groupId}}

**Comment by laura-rodriguez** [comment]
@nbarbettini first use case doesn't look to refer to a group scenario.
